export interface KanaChar {
  kana: string
  romaji: string
  type: 'hiragana' | 'katakana'
  group: string
}

export const HIRAGANA: KanaChar[] = [
  // Vowels
  { kana: 'あ', romaji: 'a', type: 'hiragana', group: 'vowels' },
  { kana: 'い', romaji: 'i', type: 'hiragana', group: 'vowels' },
  { kana: 'う', romaji: 'u', type: 'hiragana', group: 'vowels' },
  { kana: 'え', romaji: 'e', type: 'hiragana', group: 'vowels' },
  { kana: 'お', romaji: 'o', type: 'hiragana', group: 'vowels' },
  // K group
  { kana: 'か', romaji: 'ka', type: 'hiragana', group: 'k' },
  { kana: 'き', romaji: 'ki', type: 'hiragana', group: 'k' },
  { kana: 'く', romaji: 'ku', type: 'hiragana', group: 'k' },
  { kana: 'け', romaji: 'ke', type: 'hiragana', group: 'k' },
  { kana: 'こ', romaji: 'ko', type: 'hiragana', group: 'k' },
  // S group
  { kana: 'さ', romaji: 'sa', type: 'hiragana', group: 's' },
  { kana: 'し', romaji: 'shi', type: 'hiragana', group: 's' },
  { kana: 'す', romaji: 'su', type: 'hiragana', group: 's' },
  { kana: 'せ', romaji: 'se', type: 'hiragana', group: 's' },
  { kana: 'そ', romaji: 'so', type: 'hiragana', group: 's' },
  // T group
  { kana: 'た', romaji: 'ta', type: 'hiragana', group: 't' },
  { kana: 'ち', romaji: 'chi', type: 'hiragana', group: 't' },
  { kana: 'つ', romaji: 'tsu', type: 'hiragana', group: 't' },
  { kana: 'て', romaji: 'te', type: 'hiragana', group: 't' },
  { kana: 'と', romaji: 'to', type: 'hiragana', group: 't' },
  // N group
  { kana: 'な', romaji: 'na', type: 'hiragana', group: 'n' },
  { kana: 'に', romaji: 'ni', type: 'hiragana', group: 'n' },
  { kana: 'ぬ', romaji: 'nu', type: 'hiragana', group: 'n' },
  { kana: 'ね', romaji: 'ne', type: 'hiragana', group: 'n' },
  { kana: 'の', romaji: 'no', type: 'hiragana', group: 'n' },
  // H group
  { kana: 'は', romaji: 'ha', type: 'hiragana', group: 'h' },
  { kana: 'ひ', romaji: 'hi', type: 'hiragana', group: 'h' },
  { kana: 'ふ', romaji: 'fu', type: 'hiragana', group: 'h' },
  { kana: 'へ', romaji: 'he', type: 'hiragana', group: 'h' },
  { kana: 'ほ', romaji: 'ho', type: 'hiragana', group: 'h' },
  // M group
  { kana: 'ま', romaji: 'ma', type: 'hiragana', group: 'm' },
  { kana: 'み', romaji: 'mi', type: 'hiragana', group: 'm' },
  { kana: 'む', romaji: 'mu', type: 'hiragana', group: 'm' },
  { kana: 'め', romaji: 'me', type: 'hiragana', group: 'm' },
  { kana: 'も', romaji: 'mo', type: 'hiragana', group: 'm' },
  // Y group
  { kana: 'や', romaji: 'ya', type: 'hiragana', group: 'y' },
  { kana: 'ゆ', romaji: 'yu', type: 'hiragana', group: 'y' },
  { kana: 'よ', romaji: 'yo', type: 'hiragana', group: 'y' },
  // R group
  { kana: 'ら', romaji: 'ra', type: 'hiragana', group: 'r' },
  { kana: 'り', romaji: 'ri', type: 'hiragana', group: 'r' },
  { kana: 'る', romaji: 'ru', type: 'hiragana', group: 'r' },
  { kana: 'れ', romaji: 're', type: 'hiragana', group: 'r' },
  { kana: 'ろ', romaji: 'ro', type: 'hiragana', group: 'r' },
  // W group
  { kana: 'わ', romaji: 'wa', type: 'hiragana', group: 'w' },
  { kana: 'を', romaji: 'wo', type: 'hiragana', group: 'w' },
  { kana: 'ん', romaji: 'n', type: 'hiragana', group: 'n-standalone' },
  // Dakuten G
  { kana: 'が', romaji: 'ga', type: 'hiragana', group: 'g' },
  { kana: 'ぎ', romaji: 'gi', type: 'hiragana', group: 'g' },
  { kana: 'ぐ', romaji: 'gu', type: 'hiragana', group: 'g' },
  { kana: 'げ', romaji: 'ge', type: 'hiragana', group: 'g' },
  { kana: 'ご', romaji: 'go', type: 'hiragana', group: 'g' },
  // Dakuten Z
  { kana: 'ざ', romaji: 'za', type: 'hiragana', group: 'z' },
  { kana: 'じ', romaji: 'ji', type: 'hiragana', group: 'z' },
  { kana: 'ず', romaji: 'zu', type: 'hiragana', group: 'z' },
  { kana: 'ぜ', romaji: 'ze', type: 'hiragana', group: 'z' },
  { kana: 'ぞ', romaji: 'zo', type: 'hiragana', group: 'z' },
  // Dakuten D
  { kana: 'だ', romaji: 'da', type: 'hiragana', group: 'd' },
  { kana: 'ぢ', romaji: 'ji', type: 'hiragana', group: 'd' },
  { kana: 'づ', romaji: 'zu', type: 'hiragana', group: 'd' },
  { kana: 'で', romaji: 'de', type: 'hiragana', group: 'd' },
  { kana: 'ど', romaji: 'do', type: 'hiragana', group: 'd' },
  // Dakuten B
  { kana: 'ば', romaji: 'ba', type: 'hiragana', group: 'b' },
  { kana: 'び', romaji: 'bi', type: 'hiragana', group: 'b' },
  { kana: 'ぶ', romaji: 'bu', type: 'hiragana', group: 'b' },
  { kana: 'べ', romaji: 'be', type: 'hiragana', group: 'b' },
  { kana: 'ぼ', romaji: 'bo', type: 'hiragana', group: 'b' },
  // Handakuten P
  { kana: 'ぱ', romaji: 'pa', type: 'hiragana', group: 'p' },
  { kana: 'ぴ', romaji: 'pi', type: 'hiragana', group: 'p' },
  { kana: 'ぷ', romaji: 'pu', type: 'hiragana', group: 'p' },
  { kana: 'ぺ', romaji: 'pe', type: 'hiragana', group: 'p' },
  { kana: 'ぽ', romaji: 'po', type: 'hiragana', group: 'p' },
]

export const KATAKANA: KanaChar[] = [
  { kana: 'ア', romaji: 'a', type: 'katakana', group: 'vowels' },
  { kana: 'イ', romaji: 'i', type: 'katakana', group: 'vowels' },
  { kana: 'ウ', romaji: 'u', type: 'katakana', group: 'vowels' },
  { kana: 'エ', romaji: 'e', type: 'katakana', group: 'vowels' },
  { kana: 'オ', romaji: 'o', type: 'katakana', group: 'vowels' },
  { kana: 'カ', romaji: 'ka', type: 'katakana', group: 'k' },
  { kana: 'キ', romaji: 'ki', type: 'katakana', group: 'k' },
  { kana: 'ク', romaji: 'ku', type: 'katakana', group: 'k' },
  { kana: 'ケ', romaji: 'ke', type: 'katakana', group: 'k' },
  { kana: 'コ', romaji: 'ko', type: 'katakana', group: 'k' },
  { kana: 'サ', romaji: 'sa', type: 'katakana', group: 's' },
  { kana: 'シ', romaji: 'shi', type: 'katakana', group: 's' },
  { kana: 'ス', romaji: 'su', type: 'katakana', group: 's' },
  { kana: 'セ', romaji: 'se', type: 'katakana', group: 's' },
  { kana: 'ソ', romaji: 'so', type: 'katakana', group: 's' },
  { kana: 'タ', romaji: 'ta', type: 'katakana', group: 't' },
  { kana: 'チ', romaji: 'chi', type: 'katakana', group: 't' },
  { kana: 'ツ', romaji: 'tsu', type: 'katakana', group: 't' },
  { kana: 'テ', romaji: 'te', type: 'katakana', group: 't' },
  { kana: 'ト', romaji: 'to', type: 'katakana', group: 't' },
  { kana: 'ナ', romaji: 'na', type: 'katakana', group: 'n' },
  { kana: 'ニ', romaji: 'ni', type: 'katakana', group: 'n' },
  { kana: 'ヌ', romaji: 'nu', type: 'katakana', group: 'n' },
  { kana: 'ネ', romaji: 'ne', type: 'katakana', group: 'n' },
  { kana: 'ノ', romaji: 'no', type: 'katakana', group: 'n' },
  { kana: 'ハ', romaji: 'ha', type: 'katakana', group: 'h' },
  { kana: 'ヒ', romaji: 'hi', type: 'katakana', group: 'h' },
  { kana: 'フ', romaji: 'fu', type: 'katakana', group: 'h' },
  { kana: 'ヘ', romaji: 'he', type: 'katakana', group: 'h' },
  { kana: 'ホ', romaji: 'ho', type: 'katakana', group: 'h' },
  { kana: 'マ', romaji: 'ma', type: 'katakana', group: 'm' },
  { kana: 'ミ', romaji: 'mi', type: 'katakana', group: 'm' },
  { kana: 'ム', romaji: 'mu', type: 'katakana', group: 'm' },
  { kana: 'メ', romaji: 'me', type: 'katakana', group: 'm' },
  { kana: 'モ', romaji: 'mo', type: 'katakana', group: 'm' },
  { kana: 'ヤ', romaji: 'ya', type: 'katakana', group: 'y' },
  { kana: 'ユ', romaji: 'yu', type: 'katakana', group: 'y' },
  { kana: 'ヨ', romaji: 'yo', type: 'katakana', group: 'y' },
  { kana: 'ラ', romaji: 'ra', type: 'katakana', group: 'r' },
  { kana: 'リ', romaji: 'ri', type: 'katakana', group: 'r' },
  { kana: 'ル', romaji: 'ru', type: 'katakana', group: 'r' },
  { kana: 'レ', romaji: 're', type: 'katakana', group: 'r' },
  { kana: 'ロ', romaji: 'ro', type: 'katakana', group: 'r' },
  { kana: 'ワ', romaji: 'wa', type: 'katakana', group: 'w' },
  { kana: 'ヲ', romaji: 'wo', type: 'katakana', group: 'w' },
  { kana: 'ン', romaji: 'n', type: 'katakana', group: 'n-standalone' },
  { kana: 'ガ', romaji: 'ga', type: 'katakana', group: 'g' },
  { kana: 'ギ', romaji: 'gi', type: 'katakana', group: 'g' },
  { kana: 'グ', romaji: 'gu', type: 'katakana', group: 'g' },
  { kana: 'ゲ', romaji: 'ge', type: 'katakana', group: 'g' },
  { kana: 'ゴ', romaji: 'go', type: 'katakana', group: 'g' },
  { kana: 'ザ', romaji: 'za', type: 'katakana', group: 'z' },
  { kana: 'ジ', romaji: 'ji', type: 'katakana', group: 'z' },
  { kana: 'ズ', romaji: 'zu', type: 'katakana', group: 'z' },
  { kana: 'ゼ', romaji: 'ze', type: 'katakana', group: 'z' },
  { kana: 'ゾ', romaji: 'zo', type: 'katakana', group: 'z' },
  { kana: 'ダ', romaji: 'da', type: 'katakana', group: 'd' },
  { kana: 'デ', romaji: 'de', type: 'katakana', group: 'd' },
  { kana: 'ド', romaji: 'do', type: 'katakana', group: 'd' },
  { kana: 'バ', romaji: 'ba', type: 'katakana', group: 'b' },
  { kana: 'ビ', romaji: 'bi', type: 'katakana', group: 'b' },
  { kana: 'ブ', romaji: 'bu', type: 'katakana', group: 'b' },
  { kana: 'ベ', romaji: 'be', type: 'katakana', group: 'b' },
  { kana: 'ボ', romaji: 'bo', type: 'katakana', group: 'b' },
  { kana: 'パ', romaji: 'pa', type: 'katakana', group: 'p' },
  { kana: 'ピ', romaji: 'pi', type: 'katakana', group: 'p' },
  { kana: 'プ', romaji: 'pu', type: 'katakana', group: 'p' },
  { kana: 'ペ', romaji: 'pe', type: 'katakana', group: 'p' },
  { kana: 'ポ', romaji: 'po', type: 'katakana', group: 'p' },
]

export const ALL_KANA = [...HIRAGANA, ...KATAKANA]

// Grid layout for display (5 columns: a i u e o)
export const HIRAGANA_GRID = [
  ['あ', 'い', 'う', 'え', 'お'],
  ['か', 'き', 'く', 'け', 'こ'],
  ['さ', 'し', 'す', 'せ', 'そ'],
  ['た', 'ち', 'つ', 'て', 'と'],
  ['な', 'に', 'ぬ', 'ね', 'の'],
  ['は', 'ひ', 'ふ', 'へ', 'ほ'],
  ['ま', 'み', 'む', 'め', 'も'],
  ['や', '', 'ゆ', '', 'よ'],
  ['ら', 'り', 'る', 'れ', 'ろ'],
  ['わ', '', '', '', 'を'],
  ['ん', '', '', '', ''],
]

export const KATAKANA_GRID = [
  ['ア', 'イ', 'ウ', 'エ', 'オ'],
  ['カ', 'キ', 'ク', 'ケ', 'コ'],
  ['サ', 'シ', 'ス', 'セ', 'ソ'],
  ['タ', 'チ', 'ツ', 'テ', 'ト'],
  ['ナ', 'ニ', 'ヌ', 'ネ', 'ノ'],
  ['ハ', 'ヒ', 'フ', 'ヘ', 'ホ'],
  ['マ', 'ミ', 'ム', 'メ', 'モ'],
  ['ヤ', '', 'ユ', '', 'ヨ'],
  ['ラ', 'リ', 'ル', 'レ', 'ロ'],
  ['ワ', '', '', '', 'ヲ'],
  ['ン', '', '', '', ''],
]

export const ROMAJI_MAP: Record<string, string> = {
  'あ': 'a', 'い': 'i', 'う': 'u', 'え': 'e', 'お': 'o',
  'か': 'ka', 'き': 'ki', 'く': 'ku', 'け': 'ke', 'こ': 'ko',
  'さ': 'sa', 'し': 'shi', 'す': 'su', 'せ': 'se', 'そ': 'so',
  'た': 'ta', 'ち': 'chi', 'つ': 'tsu', 'て': 'te', 'と': 'to',
  'な': 'na', 'に': 'ni', 'ぬ': 'nu', 'ね': 'ne', 'の': 'no',
  'は': 'ha', 'ひ': 'hi', 'ふ': 'fu', 'へ': 'he', 'ほ': 'ho',
  'ま': 'ma', 'み': 'mi', 'む': 'mu', 'め': 'me', 'も': 'mo',
  'や': 'ya', 'ゆ': 'yu', 'よ': 'yo',
  'ら': 'ra', 'り': 'ri', 'る': 'ru', 'れ': 're', 'ろ': 'ro',
  'わ': 'wa', 'を': 'wo', 'ん': 'n',
  'が': 'ga', 'ぎ': 'gi', 'ぐ': 'gu', 'げ': 'ge', 'ご': 'go',
  'ざ': 'za', 'じ': 'ji', 'ず': 'zu', 'ぜ': 'ze', 'ぞ': 'zo',
  'だ': 'da', 'ぢ': 'ji', 'づ': 'zu', 'で': 'de', 'ど': 'do',
  'ば': 'ba', 'び': 'bi', 'ぶ': 'bu', 'べ': 'be', 'ぼ': 'bo',
  'ぱ': 'pa', 'ぴ': 'pi', 'ぷ': 'pu', 'ぺ': 'pe', 'ぽ': 'po',
  'ア': 'a', 'イ': 'i', 'ウ': 'u', 'エ': 'e', 'オ': 'o',
  'カ': 'ka', 'キ': 'ki', 'ク': 'ku', 'ケ': 'ke', 'コ': 'ko',
  'サ': 'sa', 'シ': 'shi', 'ス': 'su', 'セ': 'se', 'ソ': 'so',
  'タ': 'ta', 'チ': 'chi', 'ツ': 'tsu', 'テ': 'te', 'ト': 'to',
  'ナ': 'na', 'ニ': 'ni', 'ヌ': 'nu', 'ネ': 'ne', 'ノ': 'no',
  'ハ': 'ha', 'ヒ': 'hi', 'フ': 'fu', 'ヘ': 'he', 'ホ': 'ho',
  'マ': 'ma', 'ミ': 'mi', 'ム': 'mu', 'メ': 'me', 'モ': 'mo',
  'ヤ': 'ya', 'ユ': 'yu', 'ヨ': 'yo',
  'ラ': 'ra', 'リ': 'ri', 'ル': 'ru', 'レ': 're', 'ロ': 'ro',
  'ワ': 'wa', 'ヲ': 'wo', 'ン': 'n',
  'ガ': 'ga', 'ギ': 'gi', 'グ': 'gu', 'ゲ': 'ge', 'ゴ': 'go',
  'ザ': 'za', 'ジ': 'ji', 'ズ': 'zu', 'ゼ': 'ze', 'ゾ': 'zo',
  'ダ': 'da', 'デ': 'de', 'ド': 'do',
  'バ': 'ba', 'ビ': 'bi', 'ブ': 'bu', 'ベ': 'be', 'ボ': 'bo',
  'パ': 'pa', 'ピ': 'pi', 'プ': 'pu', 'ペ': 'pe', 'ポ': 'po',
}
