// N5/N4 reading passages for reading practice
// Furigana format: [kanji|reading] inline markers, parsed by renderWithFurigana()

export interface ReadingPassage {
  id: string
  title: string       // Japanese title
  titleEn: string     // English title
  level: 'N5' | 'N4' | 'N3' | 'N2' | 'N1'
  topic: string
  paragraphs: { japanese: string; english: string }[]
  vocabulary: { word: string; reading: string; english: string }[]
}

export const READING_PASSAGES: ReadingPassage[] = [
  {
    id: 'r001',
    title: 'じこしょうかい',
    titleEn: 'Self-Introduction',
    level: 'N5',
    topic: 'daily life',
    paragraphs: [
      {
        japanese: 'はじめまして。わたしの[名前|なまえ]はたなかゆいです。',
        english: 'Nice to meet you. My name is Yui Tanaka.',
      },
      {
        japanese: 'わたしは[東京|とうきょう]に[住|す]んでいます。[今|いま]、[大学|だいがく]で[英語|えいご]を[勉強|べんきょう]しています。',
        english: 'I live in Tokyo. Right now I am studying English at university.',
      },
      {
        japanese: '[趣味|しゅみ]はおんがくをきくことです。とくにJポップがすきです。',
        english: 'My hobby is listening to music. I especially like J-pop.',
      },
      {
        japanese: 'まいにち[学校|がっこう]のあとで、カフェでコーヒーをのみます。',
        english: 'Every day after school, I drink coffee at a café.',
      },
      {
        japanese: 'どうぞよろしくおねがいします。',
        english: 'I look forward to getting to know you.',
      },
    ],
    vocabulary: [
      { word: '名前', reading: 'なまえ', english: 'name' },
      { word: '住む', reading: 'すむ', english: 'to live (somewhere)' },
      { word: '勉強', reading: 'べんきょう', english: 'study' },
      { word: '趣味', reading: 'しゅみ', english: 'hobby' },
    ],
  },
  {
    id: 'r002',
    title: 'わたしのかぞく',
    titleEn: 'My Family',
    level: 'N5',
    topic: 'family',
    paragraphs: [
      {
        japanese: 'わたしのかぞくは[四人|よにん]です。',
        english: 'There are four people in my family.',
      },
      {
        japanese: 'ちちは[会社員|かいしゃいん]で、まいにち[電車|でんしゃ]で[仕事|しごと]にいきます。',
        english: 'My father is a company employee and commutes to work by train every day.',
      },
      {
        japanese: 'ははは[先生|せんせい]です。[小学校|しょうがっこう]で[子供|こども]たちをおしえています。',
        english: 'My mother is a teacher. She teaches children at an elementary school.',
      },
      {
        japanese: 'あには[大学生|だいがくせい]で、[東京|とうきょう]の[大学|だいがく]に[通|かよ]っています。',
        english: 'My older brother is a university student and attends a university in Tokyo.',
      },
      {
        japanese: 'わたしたちはとても[仲|なか]がいいです。しゅうまつはみんなでごはんをたべます。',
        english: 'We get along very well. On weekends we all eat together.',
      },
    ],
    vocabulary: [
      { word: '会社員', reading: 'かいしゃいん', english: 'company employee' },
      { word: '電車', reading: 'でんしゃ', english: 'train' },
      { word: '仕事', reading: 'しごと', english: 'work / job' },
      { word: '先生', reading: 'せんせい', english: 'teacher' },
      { word: '大学生', reading: 'だいがくせい', english: 'university student' },
    ],
  },
  {
    id: 'r003',
    title: 'まいにちのせいかつ',
    titleEn: 'My Daily Routine',
    level: 'N5',
    topic: 'daily life',
    paragraphs: [
      {
        japanese: 'わたしはまいあさろくじはんにおきます。',
        english: 'I wake up every morning at 6:30.',
      },
      {
        japanese: 'シャワーをあびてから、[朝|あさ]ごはんをたべます。だいたいパンとコーヒーです。',
        english: 'After showering, I eat breakfast. Usually it is bread and coffee.',
      },
      {
        japanese: 'しちじごろ[家|いえ]をでて、[学校|がっこう]へいきます。[電車|でんしゃ]でやくじゅっぷんかかります。',
        english: 'I leave home around 7 o\'clock and go to school. It takes about ten minutes by train.',
      },
      {
        japanese: '[昼|ひる]ごはんはともだちとたべます。よくがっこうのちかくのレストランにいきます。',
        english: 'I eat lunch with friends. We often go to a restaurant near the school.',
      },
      {
        japanese: '[夕方|ゆうがた]にかえってから、しゅくだいをして、[夜|よる]じゅうじごろねます。',
        english: 'After returning in the evening, I do homework and go to sleep around 10 PM.',
      },
    ],
    vocabulary: [
      { word: '起きる', reading: 'おきる', english: 'to wake up' },
      { word: '朝ごはん', reading: 'あさごはん', english: 'breakfast' },
      { word: '昼ごはん', reading: 'ひるごはん', english: 'lunch' },
      { word: '夕方', reading: 'ゆうがた', english: 'evening / late afternoon' },
      { word: '夜', reading: 'よる', english: 'night' },
    ],
  },
  {
    id: 'r004',
    title: 'すきなたべもの',
    titleEn: 'Food I Like',
    level: 'N5',
    topic: 'food',
    paragraphs: [
      {
        japanese: 'わたしはにほんりょうりがだいすきです。',
        english: 'I love Japanese food.',
      },
      {
        japanese: 'とくに[寿司|すし]とラーメンがすきです。まいしゅう[一回|いっかい]はたべたいとおもいます。',
        english: 'I especially like sushi and ramen. I think I want to eat them at least once a week.',
      },
      {
        japanese: '[夏|なつ]はかき[氷|こおり]がおいしいです。あまくてつめたくてさいこうです。',
        english: 'In summer, shaved ice is delicious. It\'s sweet, cold, and the best.',
      },
      {
        japanese: '[苦手|にがて]なたべものはセロリです。においがあまりすきじゃないです。',
        english: 'The food I\'m not good with is celery. I don\'t like the smell very much.',
      },
      {
        japanese: 'いつかにほんにいって、ほんものの[天ぷら|てんぷら]をたべてみたいです。',
        english: 'Someday I want to go to Japan and try real tempura.',
      },
    ],
    vocabulary: [
      { word: '寿司', reading: 'すし', english: 'sushi' },
      { word: '一回', reading: 'いっかい', english: 'once / one time' },
      { word: '苦手', reading: 'にがて', english: 'not good at / dislike' },
      { word: '天ぷら', reading: 'てんぷら', english: 'tempura' },
    ],
  },
  {
    id: 'r005',
    title: 'きせつ',
    titleEn: 'The Seasons',
    level: 'N5',
    topic: 'nature',
    paragraphs: [
      {
        japanese: 'にほんには[四|よ]つのきせつがあります。[春|はる]、[夏|なつ]、[秋|あき]、[冬|ふゆ]です。',
        english: 'Japan has four seasons: spring, summer, autumn, and winter.',
      },
      {
        japanese: '[春|はる]は[桜|さくら]がとてもきれいです。みんなこうえんで[花見|はなみ]をします。',
        english: 'In spring, cherry blossoms are very beautiful. Everyone does hanami (flower viewing) in the park.',
      },
      {
        japanese: '[夏|なつ]はあついですが、[海|うみ]やまつりがあってたのしいです。',
        english: 'Summer is hot, but it\'s fun with the sea and festivals.',
      },
      {
        japanese: '[秋|あき]はもみじの[葉|は]がきれいです。すずしくて、べんきょうにいいきせつです。',
        english: 'In autumn, the maple leaves are beautiful. It is cool and a good season for studying.',
      },
      {
        japanese: '[冬|ふゆ]はさむいですが、[雪|ゆき]がふるとけしきがとてもうつくしいです。',
        english: 'Winter is cold, but when snow falls the scenery is very beautiful.',
      },
    ],
    vocabulary: [
      { word: '桜', reading: 'さくら', english: 'cherry blossom' },
      { word: '花見', reading: 'はなみ', english: 'flower viewing' },
      { word: '海', reading: 'うみ', english: 'sea / ocean' },
      { word: '葉', reading: 'は', english: 'leaf' },
      { word: '雪', reading: 'ゆき', english: 'snow' },
    ],
  },
  {
    id: 'r006',
    title: 'わたしのまち',
    titleEn: 'My Town',
    level: 'N5',
    topic: 'places',
    paragraphs: [
      {
        japanese: 'わたしのまちは[大阪|おおさか]です。[東京|とうきょう]の[南|みなみ]にあります。',
        english: 'My town is Osaka. It is south of Tokyo.',
      },
      {
        japanese: '[大阪|おおさか]はたべものがとくにおいしいです。たこやきやおこのみやきがゆうめいです。',
        english: 'Osaka is especially famous for food. Takoyaki and okonomiyaki are well-known.',
      },
      {
        japanese: '[駅|えき]のちかくに[大|おお]きいショッピングモールがあります。よくかいものをしにいきます。',
        english: 'Near the station there is a large shopping mall. I often go there to shop.',
      },
      {
        japanese: '[近所|きんじょ]に[公園|こうえん]があって、まいあさそこをさんぽします。',
        english: 'There is a park in the neighborhood, and I walk there every morning.',
      },
      {
        japanese: 'にぎやかなまちですが、[人|ひと]がやさしくていごこちがいいです。',
        english: 'It is a lively town, but the people are kind and it is comfortable to live in.',
      },
    ],
    vocabulary: [
      { word: '大阪', reading: 'おおさか', english: 'Osaka (city)' },
      { word: '南', reading: 'みなみ', english: 'south' },
      { word: '駅', reading: 'えき', english: 'station' },
      { word: '近所', reading: 'きんじょ', english: 'neighborhood' },
      { word: '公園', reading: 'こうえん', english: 'park' },
    ],
  },
  {
    id: 'r007',
    title: 'しごとのにほんご',
    titleEn: 'Japanese at Work',
    level: 'N4',
    topic: 'business',
    paragraphs: [
      {
        japanese: '[会議|かいぎ]は[毎週|まいしゅう][月曜日|げつようび]の[午前|ごぜん]にあります。',
        english: 'There is a meeting every Monday morning.',
      },
      {
        japanese: '[部長|ぶちょう]は[報告書|ほうこくしょ]を[金曜日|きんようび]までに[提出|ていしゅつ]してほしいとおっしゃいました。',
        english: 'The department head said he would like the report submitted by Friday.',
      },
      {
        japanese: '[同僚|どうりょう]とランチをたべながら、[新|あたら]しいプロジェクトについてはなしました。',
        english: 'While eating lunch with a colleague, we talked about the new project.',
      },
      {
        japanese: '[残業|ざんぎょう]が[続|つづ]いているので、[体|からだ]に[気|き]をつけています。',
        english: 'Since overtime has been continuing, I am being careful about my health.',
      },
      {
        japanese: '[来月|らいげつ]は[出張|しゅっちょう]で[京都|きょうと]へいく[予定|よてい]です。',
        english: 'Next month I plan to go to Kyoto on a business trip.',
      },
    ],
    vocabulary: [
      { word: '会議', reading: 'かいぎ', english: 'meeting' },
      { word: '部長', reading: 'ぶちょう', english: 'department head' },
      { word: '同僚', reading: 'どうりょう', english: 'colleague' },
      { word: '残業', reading: 'ざんぎょう', english: 'overtime work' },
      { word: '出張', reading: 'しゅっちょう', english: 'business trip' },
      { word: '予定', reading: 'よてい', english: 'plan / schedule' },
    ],
  },
  {
    id: 'r008',
    title: 'りょこう',
    titleEn: 'Travel',
    level: 'N4',
    topic: 'travel',
    paragraphs: [
      {
        japanese: '[先月|せんげつ]、ともだちと[京都|きょうと]へ[旅行|りょこう]にいきました。',
        english: 'Last month, I went on a trip to Kyoto with friends.',
      },
      {
        japanese: '[新幹線|しんかんせん]で[二時間|にじかん]かかりましたが、[車窓|しゃそう]からのけしきがきれいでした。',
        english: 'It took two hours by shinkansen, but the view from the window was beautiful.',
      },
      {
        japanese: '[金閣寺|きんかくじ]はきんいろにかがやいていて、しゃしんをたくさんとりました。',
        english: 'Kinkakuji was shining gold and I took many photos.',
      },
      {
        japanese: '[夜|よる]は[祇園|ぎおん]のしょくじをたのしみました。[湯豆腐|ゆどうふ]がとくにおいしかったです。',
        english: 'In the evening we enjoyed a meal in Gion. The tofu hotpot was especially delicious.',
      },
      {
        japanese: 'また[機会|きかい]があれば、[奈良|なら]にもいってみたいとおもっています。',
        english: 'If I have the opportunity again, I\'m thinking of visiting Nara as well.',
      },
    ],
    vocabulary: [
      { word: '旅行', reading: 'りょこう', english: 'travel / trip' },
      { word: '新幹線', reading: 'しんかんせん', english: 'bullet train' },
      { word: '金閣寺', reading: 'きんかくじ', english: 'Kinkakuji (Golden Pavilion)' },
      { word: '機会', reading: 'きかい', english: 'opportunity / chance' },
    ],
  },

  // ── N5 passages ──
  {
    id: 'r009', level: 'N5', topic: 'shopping',
    title: '[買|か]い[物|もの]', titleEn: 'Shopping',
    paragraphs: [
      { japanese: '[今日|きょう]、[友達|ともだち]とスーパーに[行|い]きました。', english: 'Today I went to the supermarket with a friend.' },
      { japanese: '[野菜|やさい]と[果物|くだもの]をたくさん[買|か]いました。', english: 'We bought a lot of vegetables and fruit.' },
      { japanese: '[りんごは一つ百円|りんごはひとつひゃくえん]でした。', english: 'Apples were 100 yen each.' },
      { japanese: '[全部|ぜんぶ]で[三千|さんぜん][円|えん]でした。お[金|かね]が[足|た]りませんでした。', english: 'In total it was 3,000 yen. I didn\'t have enough money.' },
      { japanese: '[友達|ともだち]が[千|せん][円|えん][貸|か]してくれました。ありがとう！', english: 'My friend lent me 1,000 yen. Thank you!' },
    ],
    vocabulary: [
      { word: 'スーパー', reading: 'スーパー', english: 'supermarket' },
      { word: '野菜', reading: 'やさい', english: 'vegetables' },
      { word: '果物', reading: 'くだもの', english: 'fruit' },
      { word: '全部', reading: 'ぜんぶ', english: 'all / everything' },
      { word: '足りない', reading: 'たりない', english: 'not enough' },
      { word: '貸す', reading: 'かす', english: 'to lend' },
    ],
  },
  {
    id: 'r010', level: 'N5', topic: 'school',
    title: '[学校|がっこう]の[一日|いちにち]', titleEn: 'A Day at School',
    paragraphs: [
      { japanese: '[私|わたし]は[毎日|まいにち][八時|はちじ]に[学校|がっこう]に[行|い]きます。', english: 'I go to school at 8 o\'clock every day.' },
      { japanese: '[午前中|ごぜんちゅう]は[数学|すうがく]と[英語|えいご]の[授業|じゅぎょう]があります。', english: 'In the morning I have math and English classes.' },
      { japanese: '[昼|ひる]ご[飯|はん]は[友達|ともだち]と[一緒|いっしょ]に[食|た]べます。', english: 'I eat lunch together with friends.' },
      { japanese: '[午後|ごご]は[理科|りか]と[社会|しゃかい]を[勉強|べんきょう]します。', english: 'In the afternoon I study science and social studies.' },
      { japanese: '[放課後|ほうかご]はサッカーの[練習|れんしゅう]があります。[楽|たの]しいです。', english: 'After school there is soccer practice. It\'s fun.' },
    ],
    vocabulary: [
      { word: '毎日', reading: 'まいにち', english: 'every day' },
      { word: '授業', reading: 'じゅぎょう', english: 'class / lesson' },
      { word: '午後', reading: 'ごご', english: 'afternoon' },
      { word: '勉強', reading: 'べんきょう', english: 'study' },
      { word: '放課後', reading: 'ほうかご', english: 'after school' },
      { word: '練習', reading: 'れんしゅう', english: 'practice' },
    ],
  },
  {
    id: 'r011', level: 'N5', topic: 'hobby',
    title: '[趣味|しゅみ]は[音楽|おんがく]', titleEn: 'My Hobby is Music',
    paragraphs: [
      { japanese: '[私|わたし]の[趣味|しゅみ]は[音楽|おんがく]を[聴|き]くことです。', english: 'My hobby is listening to music.' },
      { japanese: '[毎日|まいにち][寝|ね]る[前|まえ]に[三十分|さんじゅっぷん]ぐらい[聴|き]きます。', english: 'Every day I listen for about 30 minutes before sleeping.' },
      { japanese: '[好|す]きなジャンルはポップスとジャズです。', english: 'My favorite genres are pop and jazz.' },
      { japanese: '[先月|せんげつ]からギターも[始|はじ]めました。むずかしいですが、[楽|たの]しいです。', english: 'I also started guitar last month. It\'s difficult but fun.' },
      { japanese: '[将来|しょうらい]は[自分|じぶん]で[曲|きょく]を[作|つく]りたいです。', english: 'In the future I want to compose my own songs.' },
    ],
    vocabulary: [
      { word: '趣味', reading: 'しゅみ', english: 'hobby' },
      { word: '聴く', reading: 'きく', english: 'to listen' },
      { word: '始める', reading: 'はじめる', english: 'to begin / start' },
      { word: '将来', reading: 'しょうらい', english: 'the future' },
      { word: '自分', reading: 'じぶん', english: 'oneself' },
      { word: '曲', reading: 'きょく', english: 'song / piece of music' },
    ],
  },
  {
    id: 'r012', level: 'N5', topic: 'weather',
    title: '[今日|きょう]の[天気|てんき]', titleEn: 'Today\'s Weather',
    paragraphs: [
      { japanese: '[今日|きょう]は[晴|は]れです。[空|そら]がとても[青|あお]いです。', english: 'Today is sunny. The sky is very blue.' },
      { japanese: '[気温|きおん]は[二十五度|にじゅうごど]で、[風|かぜ]が[少|すこ]しあります。', english: 'The temperature is 25 degrees and there is a little wind.' },
      { japanese: '[午後|ごご]から[曇|くも]りになるかもしれません。', english: 'It might become cloudy from the afternoon.' },
      { japanese: '[明日|あした]は[雨|あめ]の[予報|よほう]です。[傘|かさ]を[持|も]っていきます。', english: 'Tomorrow is forecast to rain. I will bring an umbrella.' },
      { japanese: '[週末|しゅうまつ]は[晴|は]れるといいですね。', english: 'I hope it\'s sunny on the weekend.' },
    ],
    vocabulary: [
      { word: '天気', reading: 'てんき', english: 'weather' },
      { word: '気温', reading: 'きおん', english: 'temperature' },
      { word: '曇り', reading: 'くもり', english: 'cloudy' },
      { word: '予報', reading: 'よほう', english: 'forecast' },
      { word: '傘', reading: 'かさ', english: 'umbrella' },
      { word: '週末', reading: 'しゅうまつ', english: 'weekend' },
    ],
  },
  {
    id: 'r013', level: 'N5', topic: 'transport',
    title: '[電車|でんしゃ]の[旅|たび]', titleEn: 'A Train Journey',
    paragraphs: [
      { japanese: '[昨日|きのう]、[電車|でんしゃ]で[大阪|おおさか]に[行|い]きました。', english: 'Yesterday, I went to Osaka by train.' },
      { japanese: '[東京|とうきょう]から[大阪|おおさか]まで[新幹線|しんかんせん]で[二時間半|にじかんはん]かかります。', english: 'It takes two and a half hours from Tokyo to Osaka by shinkansen.' },
      { japanese: '[車内|しゃない]でお[弁当|べんとう]を[食|た]べました。とても[美味|おい]しかったです。', english: 'I ate a bento box on the train. It was very delicious.' },
      { japanese: '[大阪|おおさか]に[着|つ]いたら、たこ[焼|や]きを[食|た]べました。', english: 'When I arrived in Osaka, I ate takoyaki.' },
      { japanese: '[次回|じかい]は[京都|きょうと]にも[行|い]きたいと[思|おも]います。', english: 'Next time I think I want to go to Kyoto as well.' },
    ],
    vocabulary: [
      { word: '電車', reading: 'でんしゃ', english: 'train (electric)' },
      { word: '新幹線', reading: 'しんかんせん', english: 'bullet train' },
      { word: '車内', reading: 'しゃない', english: 'inside the train' },
      { word: 'お弁当', reading: 'おべんとう', english: 'bento box (packed meal)' },
      { word: '着く', reading: 'つく', english: 'to arrive' },
      { word: '次回', reading: 'じかい', english: 'next time' },
    ],
  },
  {
    id: 'r014', level: 'N5', topic: 'food',
    title: '[料理|りょうり]が[好|す]き', titleEn: 'I Love Cooking',
    paragraphs: [
      { japanese: '[私|わたし]は[料理|りょうり]が[大好|だいす]きです。', english: 'I love cooking.' },
      { japanese: '[週末|しゅうまつ]はよく[台所|だいどころ]で[新|あたら]しい[料理|りょうり]を[試|ため]します。', english: 'On weekends I often try new dishes in the kitchen.' },
      { japanese: '[先週|せんしゅう]はカレーを[作|つく]りました。[玉|たま]ねぎ、[人参|にんじん]、[肉|にく]を[使|つか]いました。', english: 'Last week I made curry. I used onions, carrots, and meat.' },
      { japanese: '[家族|かぞく]みんなが「[美味|おい]しい！」と[言|い]ってくれました。', english: 'All of my family said "Delicious!"' },
      { japanese: '[次|つぎ]は[寿司|すし]を[作|つく]ってみたいです。むずかしそうですね。', english: 'Next I want to try making sushi. It seems difficult, doesn\'t it?' },
    ],
    vocabulary: [
      { word: '料理', reading: 'りょうり', english: 'cooking / cuisine' },
      { word: '台所', reading: 'だいどころ', english: 'kitchen' },
      { word: '試す', reading: 'ためす', english: 'to try / test' },
      { word: '使う', reading: 'つかう', english: 'to use' },
      { word: '家族', reading: 'かぞく', english: 'family' },
      { word: '寿司', reading: 'すし', english: 'sushi' },
    ],
  },
  {
    id: 'r015', level: 'N5', topic: 'animals',
    title: '[動物|どうぶつ]が[好|す]き', titleEn: 'I Like Animals',
    paragraphs: [
      { japanese: '[私|わたし]は[動物|どうぶつ]がとても[好|す]きです。', english: 'I like animals very much.' },
      { japanese: '[家|いえ]でねこを二[匹|ひき][飼|か]っています。[名前|なまえ]はモモとキナです。', english: 'At home I keep two cats. Their names are Momo and Kina.' },
      { japanese: '[毎日|まいにち][遊|あそ]んでいます。ふわふわで[可愛|かわい]いです。', english: 'I play with them every day. They are fluffy and cute.' },
      { japanese: '[先週|せんしゅう][動物園|どうぶつえん]に[行|い]きました。[象|ぞう]と[キリン|きりん]を[見|み]ました。', english: 'Last week I went to the zoo. I saw elephants and giraffes.' },
      { japanese: '[将来|しょうらい]は[獣医|じゅうい]になりたいと[思|おも]っています。', english: 'In the future I am thinking of becoming a veterinarian.' },
    ],
    vocabulary: [
      { word: '動物', reading: 'どうぶつ', english: 'animal' },
      { word: '飼う', reading: 'かう', english: 'to keep (a pet)' },
      { word: '可愛い', reading: 'かわいい', english: 'cute / adorable' },
      { word: '動物園', reading: 'どうぶつえん', english: 'zoo' },
      { word: '象', reading: 'ぞう', english: 'elephant' },
      { word: '獣医', reading: 'じゅうい', english: 'veterinarian' },
    ],
  },
  {
    id: 'r016', level: 'N5', topic: 'health',
    title: '[健康|けんこう]のために', titleEn: 'For Good Health',
    paragraphs: [
      { japanese: '[健康|けんこう]のために[毎日|まいにち][運動|うんどう]しています。', english: 'For my health I exercise every day.' },
      { japanese: '[朝|あさ]は[三十分|さんじゅっぷん][公園|こうえん]をジョギングします。', english: 'In the morning I jog in the park for 30 minutes.' },
      { japanese: '[食事|しょくじ]も[大切|たいせつ]です。[野菜|やさい]をたくさん[食|た]べるようにしています。', english: 'Diet is also important. I try to eat lots of vegetables.' },
      { japanese: '[睡眠|すいみん]も[七時間|ななじかん]は[取|と]るようにしています。', english: 'I also try to get seven hours of sleep.' },
      { japanese: '[体|からだ]が[元気|げんき]だと、[勉強|べんきょう]も[仕事|しごと]もうまくいきます。', english: 'When your body is well, both study and work go well.' },
    ],
    vocabulary: [
      { word: '健康', reading: 'けんこう', english: 'health' },
      { word: '運動', reading: 'うんどう', english: 'exercise' },
      { word: '食事', reading: 'しょくじ', english: 'meal / diet' },
      { word: '大切', reading: 'たいせつ', english: 'important' },
      { word: '睡眠', reading: 'すいみん', english: 'sleep' },
      { word: '元気', reading: 'げんき', english: 'healthy / energetic' },
    ],
  },

  // ── N4 passages ──
  {
    id: 'r017', level: 'N4', topic: 'culture',
    title: '[日本|にほん]のお[正月|しょうがつ]', titleEn: 'Japanese New Year',
    paragraphs: [
      { japanese: 'お[正月|しょうがつ]は[日本|にほん]で[最|もっと]も[大切|たいせつ]な[祝日|しゅくじつ]の[一|ひと]つです。', english: 'New Year\'s is one of the most important holidays in Japan.' },
      { japanese: '[大晦日|おおみそか]には[家族|かぞく]でそばを[食|た]べる[習慣|しゅうかん]があります。', english: 'On New Year\'s Eve there is a custom of eating soba noodles with family.' },
      { japanese: '[元日|がんじつ]の[朝|あさ]は[初詣|はつもうで]に[行|い]き、[神社|じんじゃ]でお[祈|いの]りをします。', english: 'On New Year\'s morning people do their first shrine visit and pray at the shrine.' },
      { japanese: '[子供|こども]たちはお[年玉|としだま]という[特別|とくべつ]な[封筒|ふうとう]のお[金|かね]をもらいます。', english: 'Children receive money in special envelopes called otoshidama.' },
      { japanese: '[正月|しょうがつ]の[期間中|きかんちゅう]、[多|おお]くの[商店|しょうてん]が[休業|きゅうぎょう]します。', english: 'During the New Year\'s period many shops are closed.' },
    ],
    vocabulary: [
      { word: 'お正月', reading: 'おしょうがつ', english: 'New Year\'s holiday' },
      { word: '習慣', reading: 'しゅうかん', english: 'custom / habit' },
      { word: '初詣', reading: 'はつもうで', english: 'first shrine visit of the year' },
      { word: 'お年玉', reading: 'おとしだま', english: 'New Year\'s gift money' },
      { word: '特別', reading: 'とくべつ', english: 'special' },
      { word: '休業', reading: 'きゅうぎょう', english: 'closed for business' },
    ],
  },
  {
    id: 'r018', level: 'N4', topic: 'technology',
    title: 'スマートフォンの[使|つか]い[方|かた]', titleEn: 'How to Use a Smartphone',
    paragraphs: [
      { japanese: '[現代|げんだい]の[生活|せいかつ]にスマートフォンは[欠|か]かせません。', english: 'Smartphones are indispensable in modern life.' },
      { japanese: '[地図|ちず]アプリで[道|みち]を[調|しら]べたり、[翻訳|ほんやく]アプリで[外国語|がいこくご]を[理解|りかい]したりできます。', english: 'You can look up directions with map apps, or understand foreign languages with translation apps.' },
      { japanese: 'ただし、[使|つか]いすぎには[注意|ちゅうい]が[必要|ひつよう]です。', english: 'However, it is necessary to be careful not to overuse it.' },
      { japanese: '[食事|しょくじ]中や[会話|かいわ]中にスマホを[見|み]るのは[失礼|しつれい]です。', english: 'Looking at your smartphone during meals or conversations is rude.' },
      { japanese: '[上手|じょうず]に[使|つか]えば、[学習|がくしゅう]ツールとしてとても[役立|やくだ]ちます。', english: 'If used well, it is very useful as a learning tool.' },
    ],
    vocabulary: [
      { word: '現代', reading: 'げんだい', english: 'modern times / present day' },
      { word: '欠かせない', reading: 'かかせない', english: 'indispensable' },
      { word: '翻訳', reading: 'ほんやく', english: 'translation' },
      { word: '注意', reading: 'ちゅうい', english: 'caution / attention' },
      { word: '失礼', reading: 'しつれい', english: 'rude / impolite' },
      { word: '役立つ', reading: 'やくだつ', english: 'to be useful' },
    ],
  },
  {
    id: 'r019', level: 'N4', topic: 'environment',
    title: '[環境|かんきょう]を[守|まも]る', titleEn: 'Protecting the Environment',
    paragraphs: [
      { japanese: '[地球温暖化|ちきゅうおんだんか]は[現代|げんだい]の[大|だい]きな[問題|もんだい]です。', english: 'Global warming is a major problem of modern times.' },
      { japanese: '[私|わたし]たちは[毎日|まいにち]の[生活|せいかつ]の中でできることをすべきです。', english: 'We should do what we can within our daily lives.' },
      { japanese: 'たとえば、[電気|でんき]を[消|け]すこと、ゴミを[分別|ぶんべつ]すること、[買|か]い[物|もの]には[袋|ふくろ]を[持参|じさん]することです。', english: 'For example, turning off lights, separating garbage, and bringing your own bag when shopping.' },
      { japanese: '[小|ちい]さな[行動|こうどう]が[積|つ]み[重|かさ]なれば、[大|おお]きな[変化|へんか]につながります。', english: 'Small actions, if accumulated, will lead to big changes.' },
      { japanese: '[次|つぎ]の[世代|せだい]のために、[今|いま][行動|こうどう]することが[大切|たいせつ]です。', english: 'It is important to act now for the next generation.' },
    ],
    vocabulary: [
      { word: '環境', reading: 'かんきょう', english: 'environment' },
      { word: '地球温暖化', reading: 'ちきゅうおんだんか', english: 'global warming' },
      { word: '分別', reading: 'ぶんべつ', english: 'sorting / separation (of waste)' },
      { word: '行動', reading: 'こうどう', english: 'action / behavior' },
      { word: '変化', reading: 'へんか', english: 'change' },
      { word: '世代', reading: 'せだい', english: 'generation' },
    ],
  },
  {
    id: 'r020', level: 'N4', topic: 'relationships',
    title: '[友情|ゆうじょう]について', titleEn: 'About Friendship',
    paragraphs: [
      { japanese: '[良|よ]い[友人|ゆうじん]を[持|も]つことは[人生|じんせい]の[宝|たから]です。', english: 'Having good friends is a treasure in life.' },
      { japanese: '[友情|ゆうじょう]は[時間|じかん]をかけて[育|そだ]てるものです。', english: 'Friendship is something that is nurtured over time.' },
      { japanese: '[相手|あいて]の[気持|きも]ちを[理解|りかい]し、[尊重|そんちょう]することが[大切|たいせつ]です。', english: 'It is important to understand and respect the feelings of the other person.' },
      { japanese: '[困|こま]ったときに[助|たす]け[合|あ]えるのが[本当|ほんとう]の[友達|ともだち]です。', english: 'True friends are those who can help each other when in trouble.' },
      { japanese: '[離|はな]れていても、[心|こころ]はつながっています。', english: 'Even when apart, hearts are connected.' },
    ],
    vocabulary: [
      { word: '友情', reading: 'ゆうじょう', english: 'friendship' },
      { word: '宝', reading: 'たから', english: 'treasure' },
      { word: '育てる', reading: 'そだてる', english: 'to nurture / raise' },
      { word: '尊重', reading: 'そんちょう', english: 'respect' },
      { word: '助け合う', reading: 'たすけあう', english: 'to help each other' },
      { word: '本当', reading: 'ほんとう', english: 'true / real' },
    ],
  },
  {
    id: 'r021',
    title: '[旅行|りょこう]の[計画|けいかく]',
    titleEn: 'Travel Plans',
    level: 'N4',
    topic: 'travel',
    paragraphs: [
      { japanese: '[来月|らいげつ]、[友達|ともだち]と[京都|きょうと]に[旅行|りょこう]する[予定|よてい]です。', english: 'Next month, I am planning to travel to Kyoto with a friend.' },
      { japanese: '[京都|きょうと]には[有名|ゆうめい]なお[寺|てら]や[神社|じんじゃ]がたくさんあるので、ぜひ[行|い]きたいと[思|おも]っています。', english: 'Kyoto has many famous temples and shrines, so I really want to go.' },
      { japanese: '[宿泊|しゅくはく]するホテルはもう[予約|よやく]しました。[駅|えき]から[近|ちか]くて、[値段|ねだん]も[安|やす]かったです。', english: 'I have already booked the hotel we will stay at. It is close to the station and the price was also cheap.' },
      { japanese: '[旅行|りょこう]の[前|まえ]に、いろいろな[観光地|かんこうち]について[調|しら]べなければなりません。', english: 'Before the trip, I need to research various tourist spots.' },
      { japanese: '[友達|ともだち]と[一緒|いっしょ]に[計画|けいかく]を[立|た]てることができるので、とても[楽|たの]しみです。', english: 'I am very much looking forward to it because I can make plans together with my friend.' },
    ],
    vocabulary: [
      { word: '予定', reading: 'よてい', english: 'plan; schedule' },
      { word: '旅行', reading: 'りょこう', english: 'travel; trip' },
      { word: '宿泊', reading: 'しゅくはく', english: 'lodging; staying overnight' },
      { word: '予約', reading: 'よやく', english: 'reservation; booking' },
      { word: '観光地', reading: 'かんこうち', english: 'tourist spot; sightseeing area' },
    ],
  },
  {
    id: 'r022',
    title: '[アルバイト|あるばいと]の[経験|けいけん]',
    titleEn: 'Part-Time Job Experience',
    level: 'N4',
    topic: 'part-time job',
    paragraphs: [
      { japanese: '[去年|きょねん]から[駅|えき]の[近|ちか]くのカフェでアルバイトをしています。', english: 'Since last year, I have been working part-time at a café near the station.' },
      { japanese: '[仕事|しごと]は[主|おも]に[注文|ちゅうもん]をとったり、コーヒーを[作|つく]ったりすることです。', english: 'The job mainly involves taking orders and making coffee.' },
      { japanese: '[最初|さいしょ]はとても[緊張|きんちょう]しましたが、[今|いま]は[楽|たの]しんで[働|はたら]くことができます。', english: 'At first I was very nervous, but now I am able to work and enjoy it.' },
      { japanese: 'アルバイトを[通|とお]して、お[客|きゃく]さまとのコミュニケーションが[上手|じょうず]になったと[思|おも]います。', english: 'Through part-time work, I think my communication with customers has improved.' },
      { japanese: '[給料|きゅうりょう]は[毎月|まいつき][学費|がくひ]の[一部|いちぶ]に[使|つか]っています。[働|はたら]くことの[大切|たいせつ]さを[学|まな]ぶことができました。', english: 'Each month I use part of my wages for tuition fees. I was able to learn the importance of working.' },
    ],
    vocabulary: [
      { word: '経験', reading: 'けいけん', english: 'experience' },
      { word: '注文', reading: 'ちゅうもん', english: 'order (at a restaurant, etc.)' },
      { word: '緊張', reading: 'きんちょう', english: 'nervousness; tension' },
      { word: '給料', reading: 'きゅうりょう', english: 'wages; salary' },
      { word: '学費', reading: 'がくひ', english: 'tuition fees; school expenses' },
    ],
  },
  {
    id: 'r023',
    title: '[週末|しゅうまつ]の[過|す]ごし[方|かた]',
    titleEn: 'How I Spend My Weekends',
    level: 'N4',
    topic: 'weekend activities',
    paragraphs: [
      { japanese: '[私|わたし]は[週末|しゅうまつ]になると、よく[近所|きんじょ]の[公園|こうえん]を[散歩|さんぽ]します。', english: 'When the weekend comes, I often take a walk in the nearby park.' },
      { japanese: '[公園|こうえん]では[走|はし]ったり、[木|き]の[下|した]で[本|ほん]を[読|よ]んだりすることができます。', english: 'In the park, you can run or read books under the trees.' },
      { japanese: '[土曜日|どようび]の[午後|ごご]は[友達|ともだち]とよく[映画|えいが]を[見|み]に[行|い]きます。[最近|さいきん]は[日本語|にほんご]の[映画|えいが]もよく[見|み]るようになりました。', english: 'On Saturday afternoons, I often go to see movies with friends. Recently I have come to watch Japanese films as well.' },
      { japanese: '[日曜日|にちようび]は[家族|かぞく]と[一緒|いっしょ]に[夕食|ゆうしょく]を[作|つく]ることが[多|おお]いです。', english: 'On Sundays I often cook dinner together with my family.' },
      { japanese: '[週末|しゅうまつ]は[自分|じぶん]の[好|す]きなことができるので、[毎週|まいしゅう]とても[楽|たの]しみにしています。', english: 'I look forward to the weekend very much every week because I can do things I like.' },
    ],
    vocabulary: [
      { word: '週末', reading: 'しゅうまつ', english: 'weekend' },
      { word: '散歩', reading: 'さんぽ', english: 'walk; stroll' },
      { word: '近所', reading: 'きんじょ', english: 'neighborhood; nearby area' },
      { word: '映画', reading: 'えいが', english: 'movie; film' },
      { word: '夕食', reading: 'ゆうしょく', english: 'dinner; evening meal' },
    ],
  },
  {
    id: 'r024',
    title: '[健康|けんこう]な[生活|せいかつ]',
    titleEn: 'A Healthy Lifestyle',
    level: 'N4',
    topic: 'health habits',
    paragraphs: [
      { japanese: '[健康|けんこう]のために、[毎日|まいにち][運動|うんどう]する[習慣|しゅうかん]をつけることが[大切|たいせつ]だと[思|おも]います。', english: 'I think it is important to develop the habit of exercising every day for one\'s health.' },
      { japanese: '[私|わたし]は[毎朝|まいあさ]ジョギングを[三十分|さんじゅっぷん]するようにしています。', english: 'I make a point of jogging for thirty minutes every morning.' },
      { japanese: '[食事|しょくじ]も[大切|たいせつ]で、[野菜|やさい]や[果物|くだもの]をたくさん[食|た]べなければなりません。', english: 'Diet is also important, and you must eat a lot of vegetables and fruit.' },
      { japanese: '[夜|よる]は[早|はや]く[寝|ね]て、[十分|じゅうぶん]な[睡眠|すいみん]をとることが[体|からだ]によいです。', english: 'Going to bed early at night and getting sufficient sleep is good for the body.' },
      { japanese: '[健康|けんこう]な[生活|せいかつ]を[続|つづ]けることは[難|むずか]しいですが、[少|すこ]しずつ[努力|どりょく]することができると[思|おも]っています。', english: 'Maintaining a healthy lifestyle is difficult, but I believe it is possible to make progress little by little.' },
    ],
    vocabulary: [
      { word: '健康', reading: 'けんこう', english: 'health; healthy' },
      { word: '運動', reading: 'うんどう', english: 'exercise; physical activity' },
      { word: '習慣', reading: 'しゅうかん', english: 'habit; custom' },
      { word: '睡眠', reading: 'すいみん', english: 'sleep' },
      { word: '努力', reading: 'どりょく', english: 'effort; hard work' },
    ],
  },
  {
    id: 'r025',
    title: '[買|か]い[物|もの]の[楽|たの]しみ',
    titleEn: 'The Joy of Shopping',
    level: 'N4',
    topic: 'shopping',
    paragraphs: [
      { japanese: '[私|わたし]は[買|か]い[物|もの]が[好|す]きで、[週末|しゅうまつ]によく[商店街|しょうてんがい]や[デパート|でぱーと]に[行|い]きます。', english: 'I like shopping and often go to shopping streets or department stores on weekends.' },
      { japanese: '[洋服|ようふく]を[選|えら]ぶときは、[色|いろ]やデザインだけでなく、[値段|ねだん]も[考|かんが]えなければなりません。', english: 'When choosing clothes, you need to consider not only the color and design but also the price.' },
      { japanese: '[最近|さいきん]はインターネットで[買|か]い[物|もの]することもできますが、[実際|じっさい]に[手|て]に[取|と]って[確認|かくにん]したいと[思|おも]います。', english: 'Recently you can also shop on the internet, but I think I want to actually pick things up and check them.' },
      { japanese: '[友達|ともだち]と[一緒|いっしょ]に[買|か]い[物|もの]に[行|い]けば、いろいろな[意見|いけん]を[聞|き]くことができて[便利|べんり]です。', english: 'If you go shopping together with friends, it is convenient because you can hear various opinions.' },
      { japanese: '[買|か]い[物|もの]のあとで、カフェで[休|やす]みながら[話|はな]すのも[楽|たの]しみの[一|ひと]つです。', english: 'Resting at a café and chatting after shopping is also one of the pleasures.' },
    ],
    vocabulary: [
      { word: '商店街', reading: 'しょうてんがい', english: 'shopping street; mall' },
      { word: '洋服', reading: 'ようふく', english: 'Western-style clothes' },
      { word: '値段', reading: 'ねだん', english: 'price' },
      { word: '確認', reading: 'かくにん', english: 'confirmation; checking' },
      { word: '意見', reading: 'いけん', english: 'opinion; view' },
    ],
  },
  {
    id: 'r026',
    title: '[日本|にほん]の[四季|しき]と[文化|ぶんか]',
    titleEn: 'Japanese Seasons and Culture',
    level: 'N3',
    topic: 'Japanese seasons and culture',
    paragraphs: [
      { japanese: '[日本|にほん]には[春|はる]・[夏|なつ]・[秋|あき]・[冬|ふゆ]の[四季|しき]があり、それぞれの[季節|きせつ]に[特有|とくゆう]の[文化|ぶんか]や[行事|ぎょうじ]があります。', english: 'Japan has four seasons — spring, summer, autumn, and winter — and each season has its own unique culture and events.' },
      { japanese: '[春|はる]といえば、[桜|さくら]の[花見|はなみ]です。[公園|こうえん]や[川沿|かわぞ]いに[人々|ひとびと]が[集|あつ]まり、[花|はな]を[眺|なが]めながらお[弁当|べんとう]を[食|た]べるという[習慣|しゅうかん]があります。', english: 'Speaking of spring, there is cherry blossom viewing. People gather in parks and along rivers and have the custom of eating packed lunches while gazing at the flowers.' },
      { japanese: '[夏|なつ]には[各地|かくち]で[祭|まつ]りが[行|おこな]われ、[浴衣|ゆかた]を[着|き]て[花火|はなび]を[楽|たの]しむ[人|ひと]も[多|おお]いです。', english: 'In summer, festivals are held throughout the country, and many people enjoy fireworks while wearing yukata.' },
      { japanese: '[秋|あき]は[紅葉|こうよう]の[季節|きせつ]で、[山|やま]や[寺|てら]の[周|まわ]りが[赤|あか]や[黄色|きいろ]に[染|そ]まります。[紅葉狩|もみじが]りという[言葉|ことば]があるほど、[日本人|にほんじん]に[愛|あい]されている[行事|ぎょうじ]です。', english: 'Autumn is the season of autumn leaves, when mountains and temple surroundings turn red and yellow. It is an event so loved by Japanese people that there is even a word for leaf-viewing: momijigari.' },
      { japanese: '[冬|ふゆ]は[雪|ゆき]が[降|ふ]る[地域|ちいき]も[多|おお]く、[正月|しょうがつ]に[向|む]けた[準備|じゅんび]が[始|はじ]まります。', english: 'In winter, many regions receive snow, and preparations begin for the New Year.' },
      { japanese: '[四季|しき]の[変化|へんか]によって、[日本人|にほんじん]の[生活|せいかつ]や[価値観|かちかん]が[形成|けいせい]されてきたと[言|い]えるでしょう。', english: 'It can be said that the changes of the four seasons have shaped the lifestyle and values of Japanese people.' },
    ],
    vocabulary: [
      { word: '四季', reading: 'しき', english: 'four seasons' },
      { word: '行事', reading: 'ぎょうじ', english: 'event; seasonal observance' },
      { word: '花見', reading: 'はなみ', english: 'cherry blossom viewing' },
      { word: '紅葉', reading: 'こうよう', english: 'autumn leaves; fall foliage' },
      { word: '浴衣', reading: 'ゆかた', english: 'light cotton summer kimono' },
      { word: '価値観', reading: 'かちかん', english: 'values; sense of values' },
    ],
  },
  {
    id: 'r027',
    title: '[大学|だいがく][生活|せいかつ]について',
    titleEn: 'About University Life',
    level: 'N3',
    topic: 'university life',
    paragraphs: [
      { japanese: '[大学|だいがく]に[入学|にゅうがく]してから、[生活|せいかつ]が[大|おお]きく[変|か]わりました。', english: 'Since entering university, my life has changed greatly.' },
      { japanese: '[高校|こうこう]と[違|ちが]い、[大学|だいがく]では[自分|じぶん]で[授業|じゅぎょう]や[時間割|じかんわり]を[選|えら]ぶことになっているため、[自由|じゆう]が[増|ふ]えた[分|ぶん]、[自己管理|じこかんり]が[重要|じゅうよう]になります。', english: 'Unlike high school, at university you are supposed to choose your own classes and schedule, so as freedom increases, self-management becomes more important.' },
      { japanese: '[専門|せんもん]の[勉強|べんきょう]だけでなく、サークル[活動|かつどう]やボランティアを[通|とお]じて、さまざまな[経験|けいけん]を[積|つ]むことができます。', english: 'Not only specialized study, but through club activities and volunteering, you can accumulate a wide variety of experiences.' },
      { japanese: '[私|わたし]が[入|はい]っているゼミでは、[毎週|まいしゅう][環境問題|かんきょうもんだい]という[テーマ|てーま]について[議論|ぎろん]するようになりました。', english: 'In the seminar I belong to, we have come to discuss the theme of environmental issues every week.' },
      { japanese: '[大学|だいがく]では、[将来|しょうらい]の[進路|しんろ]について[真剣|しんけん]に[考|かんが]える[機会|きかい]も[多|おお]いです。', english: 'At university, there are also many opportunities to think seriously about future career paths.' },
      { japanese: '[大学|だいがく][生活|せいかつ]とは、[知識|ちしき]を[得|え]るだけでなく、[人間|にんげん]として[成長|せいちょう]するための[大切|たいせつ]な[時間|じかん]だと[感|かん]じています。', english: 'I feel that university life is not just about gaining knowledge, but is precious time for growing as a person.' },
    ],
    vocabulary: [
      { word: '入学', reading: 'にゅうがく', english: 'entering a school; enrollment' },
      { word: '自己管理', reading: 'じこかんり', english: 'self-management' },
      { word: '議論', reading: 'ぎろん', english: 'discussion; debate' },
      { word: '進路', reading: 'しんろ', english: 'future path; career direction' },
      { word: '成長', reading: 'せいちょう', english: 'growth; development' },
      { word: '機会', reading: 'きかい', english: 'opportunity; chance' },
    ],
  },
  {
    id: 'r028',
    title: '[環境問題|かんきょうもんだい]と[私|わたし]たち',
    titleEn: 'Environmental Issues and Us',
    level: 'N3',
    topic: 'environmental issues',
    paragraphs: [
      { japanese: '[近年|きんねん]、[地球温暖化|ちきゅうおんだんか]や[海洋汚染|かいようおせん]など、[深刻|しんこく]な[環境問題|かんきょうもんだい]が[世界中|せかいじゅう]で[注目|ちゅうもく]されています。', english: 'In recent years, serious environmental issues such as global warming and ocean pollution have been attracting attention around the world.' },
      { japanese: 'これらの[問題|もんだい]は、[人間|にんげん]の[活動|かつどう]によって[引|ひ]き[起|お]こされることが[多|おお]いため、[私|わたし]たち[一人一人|ひとりひとり]が[意識|いしき]を[変|か]える[必要|ひつよう]があります。', english: 'Since many of these problems are caused by human activity, each and every one of us needs to change our awareness.' },
      { japanese: '[日本|にほん]では、[再生可能|さいせいかのう]エネルギーの[導入|どうにゅう]が[進|すす]んでおり、[太陽光発電|たいようこうはつでん]や[風力発電|ふうりょくはつでん]を[利用|りよう]する[家庭|かてい]が[増|ふ]えています。', english: 'In Japan, the introduction of renewable energy is advancing, and households using solar power generation and wind power generation are increasing.' },
      { japanese: '[私|わたし]たちの[日常|にちじょう][生活|せいかつ]でも、ゴミを[減|へ]らしたり、[公共交通機関|こうきょうこうつうきかん]を[使|つか]ったりすることで、[環境|かんきょう]への[負担|ふたん]を[減|へ]らすことができます。', english: 'In our daily lives too, we can reduce the burden on the environment by reducing waste and using public transportation.' },
      { japanese: '[将来|しょうらい]の[世代|せだい]に[豊|ゆた]かな[地球|ちきゅう]を[残|のこ]すために、[今|いま]すぐ[行動|こうどう]することが[求|もと]められています。', english: 'In order to leave a rich planet for future generations, action right now is being called for.' },
      { japanese: '[環境問題|かんきょうもんだい]は[個人|こじん]の[努力|どりょく]だけでなく、[国|くに]や[企業|きぎょう]が[連携|れんけい]して[取|と]り[組|く]む[必要|ひつよう]があるという[考|かんが]え[方|かた]も[広|ひろ]まっています。', english: 'The view that environmental issues require not only individual effort but cooperation between countries and companies is also spreading.' },
    ],
    vocabulary: [
      { word: '環境問題', reading: 'かんきょうもんだい', english: 'environmental issues' },
      { word: '深刻', reading: 'しんこく', english: 'serious; grave' },
      { word: '再生可能エネルギー', reading: 'さいせいかのうえねるぎー', english: 'renewable energy' },
      { word: '負担', reading: 'ふたん', english: 'burden; load' },
      { word: '連携', reading: 'れんけい', english: 'cooperation; coordination' },
      { word: '導入', reading: 'どうにゅう', english: 'introduction; adoption' },
    ],
  },
  {
    id: 'r029',
    title: '[技術|ぎじゅつ]と[日常|にちじょう][生活|せいかつ]',
    titleEn: 'Technology and Daily Life',
    level: 'N3',
    topic: 'technology in daily life',
    paragraphs: [
      { japanese: '[現代|げんだい]では、テクノロジーが[私|わたし]たちの[日常|にちじょう][生活|せいかつ]のあらゆる[場面|ばめん]に[浸透|しんとう]しています。', english: 'In the modern day, technology has permeated every scene of our daily lives.' },
      { japanese: 'スマートフォンの[普及|ふきゅう]によって、[情報|じょうほう]の[入手|にゅうしゅ]や[人|ひと]との[連絡|れんらく]が[以前|いぜん]と[比|くら]べて[非常|ひじょう]に[便利|べんり]になりました。', english: 'Due to the spread of smartphones, obtaining information and contacting people has become extremely convenient compared to before.' },
      { japanese: '[家電|かでん]の[分野|ぶんや]でも、AIを[搭載|とうさい]した[製品|せいひん]が[増|ふ]え、[家事|かじ]を[助|たす]けるロボット[掃除機|そうじき]や[自動|じどう]で[温度|おんど]を[調節|ちょうせつ]するエアコンなどが[一般的|いっぱんてき]になっています。', english: 'In the field of home appliances too, products equipped with AI have increased, and robotic vacuum cleaners that help with housework and air conditioners that automatically adjust the temperature have become common.' },
      { japanese: '一方で、テクノロジーへの[依存|いぞん]が[問題視|もんだいし]されるようになった[背景|はいけい]には、[人間関係|にんげんかんけい]の[希薄化|きはくか]や[健康|けんこう]への[影響|えいきょう]という[懸念|けねん]があります。', english: 'On the other hand, behind the increased concern about dependence on technology is the worry about the weakening of human relationships and effects on health.' },
      { japanese: '[技術|ぎじゅつ]の[進歩|しんぽ]を[上手|じょうず]に[活用|かつよう]しながら、[人間|にんげん]らしい[生活|せいかつ]のバランスを[保|たも]つことが[大切|たいせつ]だと[思|おも]います。', english: 'I think it is important to maintain a balance of a humane lifestyle while making good use of technological progress.' },
    ],
    vocabulary: [
      { word: '普及', reading: 'ふきゅう', english: 'widespread adoption; spread' },
      { word: '浸透', reading: 'しんとう', english: 'permeation; widespread penetration' },
      { word: '依存', reading: 'いぞん', english: 'dependence; reliance' },
      { word: '活用', reading: 'かつよう', english: 'practical use; utilization' },
      { word: '懸念', reading: 'けねん', english: 'concern; worry' },
      { word: '進歩', reading: 'しんぽ', english: 'progress; advance' },
    ],
  },
  {
    id: 'r030',
    title: '[伝統|でんとう][芸術|げいじゅつ]の[魅力|みりょく]',
    titleEn: 'The Charm of Traditional Arts',
    level: 'N3',
    topic: 'traditional arts',
    paragraphs: [
      { japanese: '[日本|にほん]には[能|のう]・[歌舞伎|かぶき]・[茶道|さどう]・[華道|かどう]など、[長|なが]い[歴史|れきし]を[持|も]つ[伝統|でんとう][芸術|げいじゅつ]が[数多|かずおお]く[存在|そんざい]します。', english: 'Japan has many traditional arts with a long history, such as noh theater, kabuki, tea ceremony, and flower arranging.' },
      { japanese: 'これらは[単|たん]なる[娯楽|ごらく]ではなく、[精神|せいしん]を[磨|みが]き、[礼儀|れいぎ]や[美意識|びいしき]を[育|そだ]てるものだという[考|かんが]え[方|かた]があります。', english: 'There is a view that these are not mere entertainment but things that refine the mind and cultivate manners and aesthetic sensibility.' },
      { japanese: '[茶道|さどう]について[言|い]えば、お[茶|ちゃ]を[点|た]てるという[行為|こうい]を[通|とお]じて、「[一期一会|いちごいちえ]」という[言葉|ことば]に[代表|だいひょう]されるような、[今|いま]この[瞬間|しゅんかん]を[大切|たいせつ]にする[精神|せいしん]を[学|まな]ぶことができます。', english: 'Speaking of the tea ceremony, through the act of preparing tea, you can learn the spirit of cherishing this present moment, as represented by the phrase \'ichigo ichie\' (once-in-a-lifetime encounter).' },
      { japanese: '[近年|きんねん]、[外国人|がいこくじん]の[間|あいだ]でも[日本|にほん]の[伝統文化|でんとうぶんか]への[関心|かんしん]が[高|たか]まっており、[体験|たいけん]ツアーに[参加|さんか]する[観光客|かんこうきゃく]が[増|ふ]えています。', english: 'In recent years, interest in Japanese traditional culture has been growing among foreigners, and the number of tourists participating in experience tours is increasing.' },
      { japanese: '[伝統|でんとう][芸術|げいじゅつ]を[次|つぎ]の[世代|せだい]に[伝|つた]えていくためには、[若者|わかもの]が[気軽|きがる]に[楽|たの]しめる[機会|きかい]を[作|つく]ることが[重要|じゅうよう]です。', english: 'In order to pass traditional arts on to the next generation, it is important to create opportunities for young people to enjoy them casually.' },
      { japanese: '[伝統|でんとう]と[革新|かくしん]のバランスをとりながら、[文化|ぶんか]を[守|まも]り[続|つづ]けることが、[現代|げんだい][日本|にほん]の[課題|かだい]の[一|ひと]つだと[言|い]えるでしょう。', english: 'It can be said that one of modern Japan\'s challenges is to continue protecting culture while balancing tradition and innovation.' },
    ],
    vocabulary: [
      { word: '伝統芸術', reading: 'でんとうげいじゅつ', english: 'traditional arts' },
      { word: '礼儀', reading: 'れいぎ', english: 'manners; etiquette' },
      { word: '美意識', reading: 'びいしき', english: 'aesthetic sensibility' },
      { word: '一期一会', reading: 'いちごいちえ', english: 'once-in-a-lifetime encounter (Zen concept)' },
      { word: '革新', reading: 'かくしん', english: 'innovation; reform' },
      { word: '課題', reading: 'かだい', english: 'challenge; task; issue' },
    ],
  },
  {
    id: 'r031',
    title: '[日本|にほん]の[食文化|しょくぶんか]',
    titleEn: 'Japanese Food Culture',
    level: 'N3',
    topic: 'food culture',
    paragraphs: [
      { japanese: '[日本|にほん]の[食文化|しょくぶんか]は「[和食|わしょく]」という[言葉|ことば]に[代表|だいひょう]されるように、[世界中|せかいじゅう]から[注目|ちゅうもく]されています。', english: 'Japanese food culture attracts attention from around the world, as represented by the word \'washoku\' (Japanese cuisine).' },
      { japanese: '[和食|わしょく]は、[旬|しゅん]の[食材|しょくざい]を[活|い]かし、だしのうまみを[大切|たいせつ]にするという[特徴|とくちょう]があります。', english: 'Washoku is characterized by making the most of seasonal ingredients and valuing the umami of dashi stock.' },
      { japanese: '[二〇一三年|にせんじゅうさんねん]には[和食|わしょく]がユネスコの[無形文化遺産|むけいぶんかいさん]に[登録|とうろく]されたことによって、[国際的|こくさいてき]な[評価|ひょうか]がさらに[高|たか]まりました。', english: 'When washoku was registered as a UNESCO Intangible Cultural Heritage in 2013, its international recognition rose even further.' },
      { japanese: '[現代|げんだい]では、[和食|わしょく]と[洋食|ようしょく]や[中華|ちゅうか]などが[融合|ゆうごう]した「[創作料理|そうさくりょうり]」という[新|あたら]しいスタイルも[人気|にんき]を[集|あつ]めています。', english: 'In modern times, a new style called \'creative cuisine,\' which fuses Japanese food with Western and Chinese dishes, is also gaining popularity.' },
      { japanese: '[食|た]べることは、ただの[栄養補給|えいようほきゅう]ではなく、[人|ひと]と[人|ひと]との[絆|きずな]を[深|ふか]め、[文化|ぶんか]を[伝|つた]える[大切|たいせつ]な[行為|こうい]だということが、[和食|わしょく]の[考|かんが]え[方|かた]に[表|あらわ]れています。', english: 'The idea that eating is not mere nutrition intake but an important act that deepens bonds between people and passes on culture is expressed in the philosophy of washoku.' },
      { japanese: '[日本食|にほんしょく]を[通|とお]じて[日本|にほん]の[文化|ぶんか]や[精神|せいしん]を[理解|りかい]しようとする[外国人|がいこくじん]が[増|ふ]えているのも、[和食|わしょく]の[魅力|みりょく]の[証|あかし]です。', english: 'The increasing number of foreigners who try to understand Japanese culture and spirit through Japanese food is also proof of the charm of washoku.' },
    ],
    vocabulary: [
      { word: '食文化', reading: 'しょくぶんか', english: 'food culture' },
      { word: '旬', reading: 'しゅん', english: 'peak season; seasonal freshness' },
      { word: '食材', reading: 'しょくざい', english: 'ingredients; foodstuffs' },
      { word: '無形文化遺産', reading: 'むけいぶんかいさん', english: 'Intangible Cultural Heritage' },
      { word: '融合', reading: 'ゆうごう', english: 'fusion; blending' },
      { word: '絆', reading: 'きずな', english: 'bond; tie (between people)' },
    ],
  },
  {
    id: 'r032',
    title: '[都市|とし]と[田舎|いなか]の[違|ちが]い',
    titleEn: 'The Difference Between City and Countryside',
    level: 'N3',
    topic: 'city vs. countryside',
    paragraphs: [
      { japanese: '[日本|にほん]では、[東京|とうきょう]や[大阪|おおさか]などの[大都市|だいとし]に[人口|じんこう]が[集中|しゅうちゅう]する[一方|いっぽう]、[地方|ちほう]では[過疎化|かそか]が[進|すす]んでいます。', english: 'In Japan, while the population is concentrating in large cities such as Tokyo and Osaka, depopulation is advancing in rural areas.' },
      { japanese: '[都市|とし]に[住|す]むことの[利点|りてん]としては、[交通|こうつう]の[便|べん]がよく、[仕事|しごと]や[教育|きょういく]の[機会|きかい]が[豊富|ほうふ]だということが[挙|あ]げられます。', english: 'The advantages of living in the city include good transportation access and abundant opportunities for work and education.' },
      { japanese: '[田舎|いなか]では[自然|しぜん]が[豊|ゆた]かで、[生活|せいかつ]のペースがゆっくりしているため、[精神的|せいしんてき]なゆとりを[感|かん]じやすいという[声|こえ]もあります。', english: 'There are also voices saying that in the countryside, nature is abundant and the pace of life is slow, making it easier to feel mental ease.' },
      { japanese: '[最近|さいきん]は、リモートワークの[普及|ふきゅう]によって、[都市|とし]を[離|はな]れて[田舎|いなか]で[働|はたら]くという[選択肢|せんたくし]を[選|えら]ぶ[人|ひと]が[増|ふ]えるようになりました。', english: 'Recently, due to the spread of remote work, the number of people choosing the option of leaving the city to work in the countryside has increased.' },
      { japanese: 'どちらの[生活|せいかつ]スタイルにも[長所|ちょうしょ]と[短所|たんしょ]があり、[個人|こじん]の[価値観|かちかん]によって[向|む]き[不向|ふむ]きがあります。', english: 'Each lifestyle has its merits and demerits, and which suits a person depends on their personal values.' },
      { japanese: '[都市|とし]と[田舎|いなか]のそれぞれの[特徴|とくちょう]を[理解|りかい]した[上|うえ]で、[自分|じぶん]に[合|あ]った[生|い]き[方|かた]を[選|えら]ぶことが[大切|たいせつ]ではないでしょうか。', english: 'Isn\'t it important to understand the characteristics of both city and countryside and then choose a way of living that suits yourself?' },
    ],
    vocabulary: [
      { word: '過疎化', reading: 'かそか', english: 'depopulation; rural decline' },
      { word: '利点', reading: 'りてん', english: 'advantage; merit' },
      { word: '選択肢', reading: 'せんたくし', english: 'option; choice' },
      { word: '長所', reading: 'ちょうしょ', english: 'strong point; advantage' },
      { word: '向き不向き', reading: 'むきふむき', english: 'what suits and doesn\'t suit someone' },
      { word: '集中', reading: 'しゅうちゅう', english: 'concentration; centralization' },
    ],
  },
  {
    id: 'r033',
    title: '[日本|にほん]で[働|はたら]くということ',
    titleEn: 'Working in Japan',
    level: 'N3',
    topic: 'working in Japan',
    paragraphs: [
      { japanese: '[日本|にほん]の[職場|しょくば]には、[独自|どくじ]の[文化|ぶんか]やルールがあります。たとえば、「[報告|ほうこく]・[連絡|れんらく]・[相談|そうだん]」を[意味|いみ]する「ほうれんそう」という[言葉|ことば]が[職場|しょくば]でよく[使|つか]われます。', english: 'Japanese workplaces have unique culture and rules. For example, the word \'ho-ren-so,\' meaning \'report, contact, consult,\' is often used in the workplace.' },
      { japanese: '[日本|にほん]の[会社|かいしゃ]では、[上司|じょうし]や[先輩|せんぱい]との[関係|かんけい]を[大切|たいせつ]にするため、[言葉|ことば]の[使|つか]い[方|かた]や[態度|たいど]に[気|き]を[配|くば]る[必要|ひつよう]があります。', english: 'In Japanese companies, because relationships with superiors and senior colleagues are valued, you need to pay attention to the way you use language and your attitude.' },
      { japanese: '[残業|ざんぎょう]が[多|おお]いという[印象|いんしょう]を[持|も]つ[外国人|がいこくじん]も[多|おお]いですが、[近年|きんねん]は[働|はたら]き[方|かた][改革|かいかく]によって[状況|じょうきょう]が[変|か]わりつつあります。', english: 'Many foreigners have the impression that there is a lot of overtime, but in recent years the situation is changing due to work-style reform.' },
      { japanese: '[外国人|がいこくじん][労働者|ろうどうしゃ]が[増|ふ]えるにともない、[職場|しょくば]の[多様性|たようせい]についての[議論|ぎろん]も[盛|さか]んになっています。', english: 'As the number of foreign workers increases, discussion about workplace diversity is also becoming more lively.' },
      { japanese: '[仕事|しごと]に[対|たい]する[姿勢|しせい]は[国|くに]や[文化|ぶんか]によって[異|こと]なるため、[異文化理解|いぶんかりかい]が[重要|じゅうよう]だという[考|かんが]え[方|かた]も[広|ひろ]まっています。', english: 'Since attitudes toward work differ by country and culture, the view that cross-cultural understanding is important is also spreading.' },
      { japanese: '[日本|にほん]で[働|はたら]くことに[興味|きょうみ]を[持|も]っている[人|ひと]は、まず[日本語|にほんご]の[学習|がくしゅう]と[文化|ぶんか]の[理解|りかい]から[始|はじ]めることが[大切|たいせつ]です。', english: 'For people who are interested in working in Japan, it is important to start with learning Japanese and understanding the culture.' },
    ],
    vocabulary: [
      { word: '職場', reading: 'しょくば', english: 'workplace' },
      { word: '残業', reading: 'ざんぎょう', english: 'overtime work' },
      { word: '働き方改革', reading: 'はたらきかたかいかく', english: 'work-style reform' },
      { word: '多様性', reading: 'たようせい', english: 'diversity' },
      { word: '姿勢', reading: 'しせい', english: 'attitude; posture' },
      { word: '異文化理解', reading: 'いぶんかりかい', english: 'cross-cultural understanding' },
    ],
  },
  {
    id: 'r034',
    title: '[日本|にほん]の[職場|しょくば][文化|ぶんか]',
    titleEn: 'Japanese Workplace Culture',
    level: 'N2',
    topic: 'Japanese workplace culture',
    paragraphs: [
      { japanese: '[日本|にほん]の[企業|きぎょう]において、[独自|どくじ]の[職場|しょくば][文化|ぶんか]が[形成|けいせい]されてきたことは[広|ひろ]く[知|し]られている。', english: 'It is widely known that a unique workplace culture has been formed in Japanese companies.' },
      { japanese: '「[空気|くうき]を[読|よ]む」という[能力|のうりょく]に[代表|だいひょう]されるように、[日本|にほん]の[職場|しょくば]では[明示|めいじ]的な[指示|しじ]がなくとも[周囲|しゅうい]の[状況|じょうきょう]を[察|さっ]して[行動|こうどう]することが[求|もと]められる。', english: 'As represented by the ability to \'read the atmosphere,\' in Japanese workplaces one is expected to sense the surrounding situation and act accordingly even without explicit instructions.' },
      { japanese: '[集団|しゅうだん][主義|しゅぎ]的な[傾向|けいこう]に[伴|ともな]い、[個人|こじん]の[意見|いけん]よりも[組織|そしき]の[和|わ]を[優先|ゆうせん]する[意識|いしき]が[根付|ねづ]いており、これが[意思決定|いしけってい]の[遅|おそ]さにつながるという[指摘|してき]もある。', english: 'Accompanying collectivist tendencies, a consciousness of prioritizing organizational harmony over individual opinions is entrenched, and there are also observations that this leads to slow decision-making.' },
      { japanese: '[一方|いっぽう]、[細部|さいぶ]への[注意|ちゅうい]や[顧客|こきゃく]への[丁寧|ていねい]な[対応|たいおう]など、[日本|にほん]の[職場|しょくば]から[生|う]まれた「[おもてなし]」の[精神|せいしん]は、[国際的|こくさいてき]に[高|たか]い[評価|ひょうか]を[受|う]けている。', english: 'On the other hand, the spirit of \'omotenashi\' born from Japanese workplaces, including attention to detail and courteous treatment of customers, has received high international regard.' },
      { japanese: '[近年|きんねん]の[労働力不足|ろうどうりょくぶそく]および[グローバル化|ぐろーばるか]の[進展|しんてん]にもかかわらず、[旧来|きゅうらい]の[慣行|かんこう]を[維持|いじ]しようとする[傾向|けいこう]が[一部|いちぶ]の[組織|そしき]において[根強|ねづよ]く[残|のこ]っている。', english: 'Despite recent labor shortages and advancing globalization, a tendency to maintain old practices persists stubbornly in some organizations.' },
      { japanese: '[職場環境|しょくばかんきょう]の[改善|かいぜん]に[基|もと]づいた[政策|せいさく]が[政府|せいふ]によって[推進|すいしん]されているが、[文化的|ぶんかてき]な[変革|へんかく]には[長|なが]い[時間|じかん]を[要|よう]するものだと[見|み]られている。', english: 'Policies based on improving the workplace environment are being promoted by the government, but cultural transformation is seen as something that requires a long time.' },
      { japanese: '[日本|にほん]の[職場|しょくば][文化|ぶんか]における[課題|かだい]を[正確|せいかく]に[把握|はあく]し、[多様|たよう]な[背景|はいけい]を[持|も]つ[人材|じんざい]が[活躍|かつやく]できる[環境|かんきょう]を[整|ととの]えることが、[今後|こんご]の[課題|かだい]となっている。', english: 'Accurately grasping the challenges in Japanese workplace culture and creating an environment where people with diverse backgrounds can play an active role has become an issue for the future.' },
    ],
    vocabulary: [
      { word: '集団主義', reading: 'しゅうだんしゅぎ', english: 'collectivism' },
      { word: '意思決定', reading: 'いしけってい', english: 'decision-making' },
      { word: '慣行', reading: 'かんこう', english: 'established practice; convention' },
      { word: 'おもてなし', reading: 'おもてなし', english: 'hospitality; attentive service' },
      { word: '変革', reading: 'へんかく', english: 'transformation; reform' },
      { word: '把握', reading: 'はあく', english: 'grasping; understanding accurately' },
      { word: '人材', reading: 'じんざい', english: 'human resources; talented personnel' },
    ],
  },
  {
    id: 'r035',
    title: '[グローバル化|ぐろーばるか]と[日本|にほん]',
    titleEn: 'Globalization and Japan',
    level: 'N2',
    topic: 'globalization',
    paragraphs: [
      { japanese: '[グローバル化|ぐろーばるか]の[進展|しんてん]に[伴|ともな]い、[日本|にほん]の[経済|けいざい]・[社会|しゃかい]・[文化|ぶんか]のあらゆる[面|めん]において、[国際的|こくさいてき]な[影響|えいきょう]が[一層|いっそう][顕著|けんちょ]になっている。', english: 'With the advance of globalization, international influences have become even more pronounced in all aspects of Japan\'s economy, society, and culture.' },
      { japanese: '[経済|けいざい]の[観点|かんてん]においては、[輸出|ゆしゅつ]への[依存|いぞん]が[高|たか]い[日本|にほん]にとって、[海外市場|かいがいしじょう]との[関係|かんけい]を[良好|りょうこう]に[保|たも]つことは[不可欠|ふかけつ]な[課題|かだい]である。', english: 'From an economic standpoint, for Japan, which has high export dependence, maintaining good relations with overseas markets is an indispensable challenge.' },
      { japanese: '[文化的|ぶんかてき]な[面|めん]にもかかわらず、アニメや[料理|りょうり]など「クールジャパン」と[呼|よ]ばれるコンテンツが[世界|せかい]で[人気|にんき]を[博|はく]しており、[日本|にほん]の[文化|ぶんか][発信力|はっしんりょく]は[確実|かくじつ]に[高|たか]まっている。', english: 'On the cultural front, content called \'Cool Japan\' such as anime and cuisine has gained popularity around the world, and Japan\'s cultural transmission power is certainly increasing.' },
      { japanese: '[少子高齢化|しょうしこうれいか]に[基|もと]づく[労働力不足|ろうどうりょくぶそく]を[補|おぎな]うため、[外国人|がいこくじん][労働者|ろうどうしゃ]の[受|う]け[入|い]れ[拡大|かくだい]が[政策|せいさく][課題|かだい]として[浮上|ふじょう]している。', english: 'To compensate for the labor shortage based on the declining birthrate and aging population, the expansion of accepting foreign workers has emerged as a policy challenge.' },
      { japanese: '[一方|いっぽう]、[外国人|がいこくじん]の[増加|ぞうか]にもかかわらず、[多文化共生|たぶんかきょうせい]に[向|む]けた[制度|せいど]や[意識|いしき]の[整備|せいび]はいまだ[不十分|ふじゅうぶん]だという[批判|ひはん]もある。', english: 'On the other hand, there is also criticism that systems and awareness toward multicultural coexistence remain insufficient, despite the increase in foreigners.' },
      { japanese: '[グローバル化|ぐろーばるか]への[対応|たいおう]において、[日本|にほん]は[独自性|どくじせい]を[保|たも]ちながら[国際標準|こくさいひょうじゅん]に[適応|てきおう]するという[難|むずか]しいバランスを[迫|せま]られている。', english: 'In responding to globalization, Japan is being pressed to strike the difficult balance of maintaining its uniqueness while adapting to international standards.' },
    ],
    vocabulary: [
      { word: 'グローバル化', reading: 'ぐろーばるか', english: 'globalization' },
      { word: '顕著', reading: 'けんちょ', english: 'remarkable; conspicuous' },
      { word: '不可欠', reading: 'ふかけつ', english: 'indispensable; essential' },
      { word: '多文化共生', reading: 'たぶんかきょうせい', english: 'multicultural coexistence' },
      { word: '独自性', reading: 'どくじせい', english: 'uniqueness; distinctiveness' },
      { word: '少子高齢化', reading: 'しょうしこうれいか', english: 'declining birthrate and aging population' },
      { word: '適応', reading: 'てきおう', english: 'adaptation; adjustment' },
    ],
  },
  {
    id: 'r036',
    title: '[超高齢社会|ちょうこうれいしゃかい]と[医療|いりょう]',
    titleEn: 'Super-Aged Society and Healthcare',
    level: 'N2',
    topic: 'health and aging society',
    paragraphs: [
      { japanese: '[日本|にほん]は[世界|せかい]に[先駆|さきが]けて「[超高齢社会|ちょうこうれいしゃかい]」に[突入|とつにゅう]し、[総人口|そうじんこう]に[占|し]める[六十五歳以上|ろくじゅうごさいいじょう]の[割合|わりあい]が[約|やく][三割|さんわり]に[達|たっ]しようとしている。', english: 'Japan has entered a \'super-aged society\' ahead of the rest of the world, with the proportion of people aged 65 and over in the total population approaching approximately 30 percent.' },
      { japanese: '[高齢化|こうれいか]に[伴|ともな]い、[医療費|いりょうひ]および[介護費用|かいごひよう]が[増大|ぞうだい]し、[社会保障制度|しゃかいほしょうせいど]の[持続可能性|じぞくかのうせい]について[深刻|しんこく]な[議論|ぎろん]が[交|か]わされている。', english: 'With aging, medical costs and nursing care expenses are increasing, and serious debate is being exchanged about the sustainability of the social security system.' },
      { japanese: '[政府|せいふ]は[予防医療|よぼういりょう]の[推進|すいしん]に[基|もと]づいた[施策|しさく]を[打|う]ち[出|だ]しており、[生活習慣病|せいかつしゅうかんびょう]の[早期発見|そうきはっけん]・[早期治療|そうきちりょう]を[目指|めざ]した[取|と]り[組|く]みが[全国|ぜんこく]で[展開|てんかい]されている。', english: 'The government has put forward measures based on promoting preventive medicine, and efforts aimed at early detection and early treatment of lifestyle-related diseases are being deployed nationwide.' },
      { japanese: '[在宅医療|ざいたくいりょう]や[地域包括|ちいきほうかつ]ケアシステムの[整備|せいび]が[進|すす]んでいるにもかかわらず、[地方|ちほう]における[医師不足|いしぶそく]は[深刻|しんこく]な[問題|もんだい]として[残|のこ]っている。', english: 'Despite progress in developing home medical care and community-based comprehensive care systems, a shortage of doctors in rural areas remains a serious problem.' },
      { japanese: '[科学技術|かがくぎじゅつ]の[進歩|しんぽ]において、AIや[遠隔診療|えんかくしんりょう]の[活用|かつよう]が[医療格差|いりょうかくさ]の[縮小|しゅくしょう]に[寄|き]与するとの[期待|きたい]が[高|たか]まっている。', english: 'With advances in science and technology, expectations are growing that the use of AI and telemedicine will contribute to reducing healthcare disparities.' },
      { japanese: '[超高齢社会|ちょうこうれいしゃかい]という[課題|かだい]に[対処|たいしょ]するためには、[医療|いりょう][制度|せいど]の[改革|かいかく]にとどまらず、[社会全体|しゃかいぜんたい]が[高齢者|こうれいしゃ]を[支|ささ]える[仕組|しく]みを[再構築|さいこうちく]する[必要|ひつよう]がある。', english: 'In order to address the challenge of a super-aged society, it is necessary not only to reform the medical system but for the whole of society to rebuild systems that support the elderly.' },
    ],
    vocabulary: [
      { word: '超高齢社会', reading: 'ちょうこうれいしゃかい', english: 'super-aged society' },
      { word: '社会保障制度', reading: 'しゃかいほしょうせいど', english: 'social security system' },
      { word: '持続可能性', reading: 'じぞくかのうせい', english: 'sustainability' },
      { word: '予防医療', reading: 'よぼういりょう', english: 'preventive medicine' },
      { word: '在宅医療', reading: 'ざいたくいりょう', english: 'home medical care' },
      { word: '医療格差', reading: 'いりょうかくさ', english: 'healthcare disparity' },
      { word: '再構築', reading: 'さいこうちく', english: 'reconstruction; rebuilding' },
    ],
  },
  {
    id: 'r037',
    title: '[日本|にほん]の[教育制度|きょういくせいど]',
    titleEn: 'Japan\'s Education System',
    level: 'N2',
    topic: 'education system',
    paragraphs: [
      { japanese: '[日本|にほん]の[教育制度|きょういくせいど]は[六三三四制|ろくさんさんよんせい]を[基本|きほん]とし、[義務教育|ぎむきょういく]は[小学校|しょうがっこう][六|ろく]年と[中学校|ちゅうがっこう][三|さん]年の[計|けい][九|く]年である。', english: 'Japan\'s education system is based on the 6-3-3-4 structure, with compulsory education consisting of six years of elementary school and three years of junior high school, totaling nine years.' },
      { japanese: '[高校|こうこう][進学率|しんがくりつ]および[大学|だいがく][進学率|しんがくりつ]はともに[高水準|こうすいじゅん]を[維持|いじ]しているが、[受験競争|じゅけんきょうそう]の[激化|げきか]に[伴|ともな]い、[子供|こども]たちにかかる[精神的|せいしんてき][負担|ふたん]が[問題視|もんだいし]されるようになっている。', english: 'Both high school and university enrollment rates remain at high levels, but with the intensification of entrance exam competition, the mental burden on children is becoming an issue.' },
      { japanese: '[文部科学省|もんぶかがくしょう]は「[生|い]きる[力|ちから]」という[概念|がいねん]に[基|もと]づき、[知識|ちしき]の[習得|しゅうとく]のみならず、[思考力|しこうりょく]・[判断力|はんだんりょく]・[表現力|ひょうげんりょく]を[育|はぐく]む[教育|きょういく]への[転換|てんかん]を[推進|すいしん]している。', english: 'The Ministry of Education, Culture, Sports, Science and Technology is promoting a shift toward education that nurtures not only knowledge acquisition but also thinking ability, judgment, and expression, based on the concept of \'zest for living.\'' },
      { japanese: '[国際化|こくさいか]に[対応|たいおう]するため、[小学校|しょうがっこう]における[英語教育|えいごきょういく]の[必修化|ひっしゅうか]が[進|すす]んでいる[一方|いっぽう]、[英語力|えいごりょく]の[向上|こうじょう]に[向|む]けた[取|と]り[組|く]みはいまだ[課題|かだい]が[多|おお]いとされている。', english: 'While the compulsory inclusion of English education in elementary schools is advancing to respond to internationalization, the efforts toward improving English proficiency are still said to face many challenges.' },
      { japanese: '[不登校|ふとうこう]や[いじめ|いじめ]の[問題|もんだい]は[依然|いぜん]として[深刻|しんこく]であり、[学校|がっこう]における[相談体制|そうだんたいせい]の[強化|きょうか]が[求|もと]められている。', english: 'The problems of school refusal and bullying remain serious, and there are demands for strengthening counseling systems at schools.' },
      { japanese: '[教育|きょういく]における[格差問題|かくさもんだい]、すなわち[家庭|かてい]の[経済状況|けいざいじょうきょう]が[子供|こども]の[学力|がくりょく]に[及|およ]ぼす[影響|えいきょう]についても、[社会的|しゃかいてき]な[関心|かんしん]が[高|たか]まっている。', english: 'Social interest is also growing regarding the problem of inequality in education, namely the influence of a family\'s financial situation on children\'s academic ability.' },
    ],
    vocabulary: [
      { word: '義務教育', reading: 'ぎむきょういく', english: 'compulsory education' },
      { word: '受験競争', reading: 'じゅけんきょうそう', english: 'entrance exam competition' },
      { word: '思考力', reading: 'しこうりょく', english: 'thinking ability; critical thinking' },
      { word: '不登校', reading: 'ふとうこう', english: 'school refusal; truancy' },
      { word: '格差問題', reading: 'かくさもんだい', english: 'inequality; disparity issue' },
      { word: '学力', reading: 'がくりょく', english: 'academic ability; scholastic achievement' },
      { word: '必修化', reading: 'ひっしゅうか', english: 'making something compulsory' },
    ],
  },
  {
    id: 'r038',
    title: '[地方創生|ちほうそうせい]の[取|と]り[組|く]み',
    titleEn: 'Regional Revitalization Efforts',
    level: 'N2',
    topic: 'regional revitalization',
    paragraphs: [
      { japanese: '[人口減少|じんこうげんしょう]と[東京|とうきょう]一[極集中|きょくしゅうちゅう]という[構造的|こうぞうてき]な[課題|かだい]に[対処|たいしょ]するため、[政府|せいふ]は「[地方創生|ちほうそうせい]」という[政策|せいさく][方針|ほうしん]を[打|う]ち[出|だ]している。', english: 'To address the structural challenges of population decline and concentration in Tokyo, the government has put forward a policy direction called \'regional revitalization.\'' },
      { japanese: 'この[政策|せいさく]においては、[各地域|かくちいき]の[特色|とくしょく]に[基|もと]づいた[産業振興|さんぎょうしんこう]や[観光資源|かんこうしげん]の[活用|かつよう]が[重視|じゅうし]されている。', english: 'In this policy, importance is placed on industrial promotion and utilization of tourist resources based on the unique characteristics of each region.' },
      { japanese: '[移住|いじゅう]・[定住|ていじゅう][促進|そくしん]に[向|む]けた[取|と]り[組|く]みとして、[地方|ちほう]への[移住者|いじゅうしゃ]に[対|たい]する[補助金|ほじょきん]の[交付|こうふ]や、リモートワーク[環境|かんきょう]の[整備|せいび]が[各自治体|かくじちたい]において[進|すす]んでいる。', english: 'As measures toward promoting migration and settlement, the provision of subsidies for those migrating to rural areas and the development of remote work environments are advancing in various local governments.' },
      { japanese: '[一部|いちぶ]の[地方都市|ちほうとし]では、[廃校|はいこう]となった[学校|がっこう][施設|しせつ]を[活用|かつよう]した[創業支援施設|そうぎょうしえんしせつ]の[設置|せっち]など、[地域資源|ちいきしげん]の[再活用|さいかつよう]に[成功|せいこう]した[事例|じれい]も[報告|ほうこく]されている。', english: 'In some regional cities, cases have also been reported of successful reuse of regional resources, such as the establishment of business start-up support facilities utilizing closed school buildings.' },
      { japanese: '[地方創生|ちほうそうせい]の[成否|せいひ]は、[中央政府|ちゅうおうせいふ]の[政策|せいさく]のみならず、[地域住民|ちいきじゅうみん]の[主体的|しゅたいてき]な[関与|かんよ]と[民間企業|みんかんきぎょう]との[連携|れんけい]にかかっているといえる。', english: 'The success or failure of regional revitalization can be said to depend not only on central government policy but on the active involvement of local residents and cooperation with private enterprises.' },
      { japanese: '[持続可能|じぞくかのう]な[地域社会|ちいきしゃかい]を[築|きず]くためには、[短期的|たんきてき]な[経済効果|けいざいこうか]を[追|お]い[求|もと]めるだけでなく、[長期的|ちょうきてき]な[視点|してん]に[立|た]った[地域|ちいき]づくりが[不可欠|ふかけつ]である。', english: 'In order to build sustainable local communities, it is essential not merely to pursue short-term economic effects but to develop communities from a long-term perspective.' },
    ],
    vocabulary: [
      { word: '地方創生', reading: 'ちほうそうせい', english: 'regional revitalization' },
      { word: '一極集中', reading: 'いっきょくしゅうちゅう', english: 'concentration in one area; unipolar concentration' },
      { word: '産業振興', reading: 'さんぎょうしんこう', english: 'industrial promotion' },
      { word: '補助金', reading: 'ほじょきん', english: 'subsidy; grant' },
      { word: '主体的', reading: 'しゅたいてき', english: 'proactive; autonomous' },
      { word: '廃校', reading: 'はいこう', english: 'school closure; closed school' },
      { word: '視点', reading: 'してん', english: 'perspective; viewpoint' },
    ],
  },
  {
    id: 'r039',
    title: '[エネルギー|えねるぎー][政策|せいさく]と[環境|かんきょう]',
    titleEn: 'Energy Policy and the Environment',
    level: 'N2',
    topic: 'energy and environment',
    paragraphs: [
      { japanese: '[二〇一一年|にせんじゅういちねん]の[東日本大震災|ひがしにほんだいしんさい]以降、[日本|にほん]の[エネルギー|えねるぎー][政策|せいさく]は[大|おお]きな[転換期|てんかんき]を[迎|むか]えた。', english: 'Following the Great East Japan Earthquake of 2011, Japan\'s energy policy entered a major turning point.' },
      { japanese: '[原子力発電|げんしりょくはつでん]への[依存度|いぞんど]が[低下|ていか]した[結果|けっか]、[再生可能|さいせいかのう]エネルギーの[導入|どうにゅう]が[一気|いっき]に[加速|かそく]したが、[電力|でんりょく][安定供給|あんていきょうきゅう]の[確保|かくほ]という[課題|かだい]も[浮|う]かび[上|あ]がった。', english: 'As a result of the decreased dependence on nuclear power generation, the introduction of renewable energy accelerated rapidly, but the challenge of ensuring a stable electricity supply also emerged.' },
      { japanese: '[政府|せいふ]は[二〇五〇年|にせんごじゅうねん]カーボンニュートラルの[実現|じつげん]に[向|む]け、[太陽光|たいようこう]・[風力|ふうりょく]・[水素|すいそ]エネルギーなどの[普及|ふきゅう]拡大を[政策|せいさく]の[柱|はしら]に[位置付|いちづ]けている。', english: 'Toward achieving carbon neutrality in 2050, the government has positioned the expansion of solar, wind, and hydrogen energy among others as pillars of policy.' },
      { japanese: '[温室効果|おんしつこうか]ガスの[排出削減|はいしゅつさくげん]に[伴|ともな]う[産業構造|さんぎょうこうぞう]の[変化|へんか]は、[一方|いっぽう]で[雇用|こよう]の[喪失|そうしつ]をもたらすという[懸念|けねん]もあり、「[公正|こうせい]な[移行|いこう]」という[概念|がいねん]が[重要視|じゅうようし]されている。', english: 'Concerns that the changes in industrial structure accompanying the reduction of greenhouse gas emissions will bring about job losses also exist, and the concept of a \'just transition\' is being given importance.' },
      { japanese: '[企業|きぎょう][レベル|れべる]においても、ESG[投資|とうし]の[拡大|かくだい]に[基|もと]づき、[環境|かんきょう][負荷|ふか]の[低減|ていげん]に[向|む]けた[取|と]り[組|く]みが[加速|かそく]しつつある。', english: 'At the corporate level too, based on the expansion of ESG investment, efforts toward reducing environmental load are accelerating.' },
      { japanese: '[エネルギー|えねるぎー][安全保障|あんぜんほしょう]と[脱炭素化|だつたんそか]という[二|ふた]つの[要請|ようせい]をいかに[両立|りょうりつ]させるかが、[現代|げんだい][日本|にほん]の[エネルギー|えねるぎー][政策|せいさく]における[根本的|こんぽんてき]な[問|と]いである。', english: 'How to simultaneously achieve the two demands of energy security and decarbonization is a fundamental question in modern Japan\'s energy policy.' },
    ],
    vocabulary: [
      { word: '再生可能エネルギー', reading: 'さいせいかのうえねるぎー', english: 'renewable energy' },
      { word: 'カーボンニュートラル', reading: 'かーぼんにゅーとらる', english: 'carbon neutrality' },
      { word: '排出削減', reading: 'はいしゅつさくげん', english: 'emissions reduction' },
      { word: '公正な移行', reading: 'こうせいないこう', english: 'just transition' },
      { word: '脱炭素化', reading: 'だつたんそか', english: 'decarbonization' },
      { word: 'エネルギー安全保障', reading: 'えねるぎーあんぜんほしょう', english: 'energy security' },
      { word: '両立', reading: 'りょうりつ', english: 'compatibility; achieving two things simultaneously' },
    ],
  },
  {
    id: 'r040',
    title: '[言語|げんご]と[思考|しこう]の[哲学|てつがく]',
    titleEn: 'The Philosophy of Language and Thought',
    level: 'N1',
    topic: 'philosophy of language',
    paragraphs: [
      { japanese: '「[言語|げんご]は[思考|しこう]の[道具|どうぐ]である」という[命題|めいだい]は、[哲学|てつがく]・[言語学|げんごがく]・[認知科学|にんちかがく]の[分野|ぶんや]において[長|なが]らく[論争|ろんそう]の[的|まと]となってきた。', english: 'The proposition that \'language is a tool of thought\' has long been a subject of controversy in the fields of philosophy, linguistics, and cognitive science.' },
      { japanese: 'ウォーフ[仮説|かせつ]が[示唆|しさ]するように、ある[概念|がいねん]を[表現|ひょうげん]する[語彙|ごい]が[存在|そんざい]しない[言語|げんご]においては、その[概念|がいねん]を[把握|はあく]すること[自体|じたい]が[困難|こんなん]になりうるという[見解|けんかい]は、[文化的|ぶんかてき][相対主義|そうたいしゅぎ]の[議論|ぎろん]と[深|ふか]く[絡|から]み[合|あ]っている。', english: 'As the Whorf hypothesis suggests, the view that in a language lacking vocabulary to express a certain concept, grasping that concept itself may become difficult is deeply intertwined with discussions of cultural relativism.' },
      { japanese: '[一方|いっぽう]で、チョムスキーらの[普遍文法|ふへんぶんぽう]の[観点|かんてん]から[言|い]えば、[言語|げんご]の[構造|こうぞう]に[先立|さきだ]ち、[人間|にんげん]には[普遍的|ふへんてき]な[認知的基盤|にんちてききばん]があるとされ、[思考|しこう]は[言語|げんご]に[還元|かんげん]されないと[主張|しゅちょう]される。', english: 'On the other hand, from the perspective of universal grammar as advocated by Chomsky and others, humans are said to have a universal cognitive foundation prior to linguistic structure, and it is argued that thought cannot be reduced to language.' },
      { japanese: '[日本語|にほんご]に[特有|とくゆう]の「[間|ま]」や「[侘|わ]び」という[概念|がいねん]は、[他言語|たげんご]に[容易|ようい]に[翻訳|ほんやく]できないことが[多|おお]く、[言語|げんご]が[世界観|せかいかん]の[形成|けいせい]に[与|あた]える[影響|えいきょう]を[示|しめ]す[具体例|ぐたいれい]として[引|ひ]き[合|あ]いに[出|だ]される。', english: 'Concepts unique to Japanese such as \'ma\' (negative space/interval) and \'wabi\' are often not easily translatable into other languages, and are cited as concrete examples showing the influence language exerts on the formation of worldview.' },
      { japanese: '[言語|げんご]を[学|まな]ぶとは、[単|たん]に[語彙|ごい]や[文法|ぶんぽう]を[習得|しゅうとく]することではなく、その[言語|げんご]が[内包|ないほう]する[世界|せかい]の[見方|みかた]に[触|ふ]れ、[自己|じこ]の[認識|にんしき]を[拡|ひろ]げることだという[見解|けんかい]は、[多|おお]くの[言語教育者|げんごきょういくしゃ]が[共有|きょうゆう]するものである。', english: 'The view that learning a language is not merely acquiring vocabulary and grammar but touching the worldview contained within that language and expanding one\'s own awareness is shared by many language educators.' },
      { japanese: '[言語|げんご]と[思考|しこう]の[関係|かんけい]をめぐる[哲学的|てつがくてき][探究|たんきゅう]は、[人工知能|じんこうちのう]の[発展|はってん]という[新|あたら]たな[文脈|ぶんみゃく]においても[再考|さいこう]を[迫|せま]られており、[人間|にんげん]の[知性|ちせい]の[本質|ほんしつ]についての[問|と]いと[不可分|ふかぶん]である。', english: 'The philosophical inquiry into the relationship between language and thought is being pressed for reconsideration in the new context of the development of artificial intelligence, and is inseparable from the question of the essence of human intellect.' },
    ],
    vocabulary: [
      { word: '命題', reading: 'めいだい', english: 'proposition; thesis' },
      { word: '語彙', reading: 'ごい', english: 'vocabulary; lexicon' },
      { word: '普遍文法', reading: 'ふへんぶんぽう', english: 'universal grammar' },
      { word: '世界観', reading: 'せかいかん', english: 'worldview' },
      { word: '内包', reading: 'ないほう', english: 'to contain; intension (in logic)' },
      { word: '探究', reading: 'たんきゅう', english: 'inquiry; exploration' },
      { word: '不可分', reading: 'ふかぶん', english: 'inseparable; indivisible' },
      { word: '還元', reading: 'かんげん', english: 'reduction; reducing to' },
    ],
  },
  {
    id: 'r041',
    title: '[近代化|きんだいか]の[歴史的|れきしてき][考察|こうさつ]',
    titleEn: 'A Historical Examination of Modernization',
    level: 'N1',
    topic: 'historical perspective on modernization',
    paragraphs: [
      { japanese: '[明治維新|めいじいしん]以降の[日本|にほん]の[近代化|きんだいか]は、[欧米|おうべい]の[文物|ぶんぶつ]を[積極的|せっきょくてき]に[取|と]り[入|い]れながらも、[固有|こゆう]の[文化的|ぶんかてき][基盤|きばん]を[保持|ほじ]しようとする[葛藤|かっとう]の[歴史|れきし]であったとも[言|い]える。', english: 'The modernization of Japan since the Meiji Restoration can also be said to have been a history of conflict — actively incorporating Western culture and civilization while trying to preserve its own cultural foundations.' },
      { japanese: '「[和魂洋才|わこんようさい]」という[標語|ひょうご]に[象徴|しょうちょう]されるように、[西洋|せいよう]の[技術|ぎじゅつ]や[制度|せいど]を[移植|いしょく]しつつも、[精神的|せいしんてき]な[核|かく]は[日本|にほん]に[固有|こゆう]のものを[守|まも]るという[理念|りねん]は、[明治|めいじ][初期|しょき]の[知識人|ちしきじん]たちの[共通|きょうつう]の[問題意識|もんだいいしき]であった。', english: 'As symbolized by the motto \'wakon yosai\' (Japanese spirit, Western technology), the idea of transplanting Western technology and institutions while preserving a spiritual core unique to Japan was a shared concern among intellectuals of the early Meiji period.' },
      { japanese: '[近代化|きんだいか]の[過程|かてい]において、[伝統的|でんとうてき]な[共同体|きょうどうたい]の[紐帯|ちゅうたい]が[解体|かいたい]され、[個人|こじん]という[概念|がいねん]が[前景化|ぜんけいか]したことは、[文学|ぶんがく]や[思想|しそう]における「[近代的|きんだいてき]自我の[目覚|めざ]め」という[主題|しゅだい]の[隆盛|りゅうせい]とも[連動|れんどう]している。', english: 'In the process of modernization, the dissolution of traditional community bonds and the foregrounding of the concept of the individual also correlates with the flourishing of the theme of \'the awakening of the modern self\' in literature and thought.' },
      { japanese: '[戦後|せんご]の[復興|ふっこう]と[高度経済成長|こうどけいざいせいちょう]は、[再|ふたた]び[日本|にほん]を[国際社会|こくさいしゃかい]の[中心|ちゅうしん]に[押|お]し[上|あ]げたが、その[豊|ゆた]かさは[精神的|せいしんてき][空洞化|くうどうか]の[問題|もんだい]を[孕|はら]んでいたとも[指摘|してき]されている。', english: 'Postwar reconstruction and the high-speed economic growth once again pushed Japan to the center of international society, but that prosperity has also been pointed out as carrying within it the problem of spiritual hollowness.' },
      { japanese: '[近代化|きんだいか]を[西洋化|せいようか]と[同一視|どういつし]するのではなく、[各|かく][文明|ぶんめい]が[固有|こゆう]の[文脈|ぶんみゃく]において[近代性|きんだいせい]を[形成|けいせい]してきたという[多元的近代論|たげんてききんだいろん]の[視点|してん]は、[日本|にほん]の[経験|けいけん]を[再|さい][評価|ひょうか]する[上|うえ]で[有益|ゆうえき]な[枠組|わくぐ]みを[提供|ていきょう]する。', english: 'The perspective of multiple modernities theory — which holds that each civilization has formed its own modernity within its own context, rather than equating modernization with Westernization — provides a useful framework for re-evaluating Japan\'s experience.' },
      { japanese: '[近代化|きんだいか]の[問題|もんだい]は[過去|かこ]の[出来事|できごと]ではなく、[現代|げんだい]の[日本|にほん]が[直面|ちょくめん]する[文化的|ぶんかてき][同一性|どういつせい]の[危機|きき]や[価値観|かちかん]の[多様化|たようか]という[問題|もんだい]とも[地続|じつづ]きである。', english: 'The issue of modernization is not a past event but is continuous with the problems of cultural identity crisis and diversification of values that modern Japan faces today.' },
    ],
    vocabulary: [
      { word: '明治維新', reading: 'めいじいしん', english: 'Meiji Restoration' },
      { word: '和魂洋才', reading: 'わこんようさい', english: 'Japanese spirit with Western knowledge' },
      { word: '紐帯', reading: 'ちゅうたい', english: 'bond; tie; link' },
      { word: '隆盛', reading: 'りゅうせい', english: 'prosperity; flourishing' },
      { word: '空洞化', reading: 'くうどうか', english: 'hollowing out; becoming empty' },
      { word: '多元的近代論', reading: 'たげんてききんだいろん', english: 'multiple modernities theory' },
      { word: '枠組み', reading: 'わくぐみ', english: 'framework; structure' },
      { word: '同一性', reading: 'どういつせい', english: 'identity; sameness' },
    ],
  },
  {
    id: 'r042',
    title: '[侘|わ]び・[寂|さ]びの[美学|びがく]',
    titleEn: 'The Aesthetics of Wabi-Sabi',
    level: 'N1',
    topic: 'traditional aesthetics (wabi-sabi)',
    paragraphs: [
      { japanese: '[侘|わ]び・[寂|さ]びとは、[不完全|ふかんぜん]さや[無常|むじょう]のうちに[深|ふか]い[美|うつく]しさを[見出|みいだ]す[日本|にほん]の[伝統的|でんとうてき]な[美意識|びいしき]であり、[西洋|せいよう]の[完璧|かんぺき]さや[恒常性|こうじょうせい]を[重|おも]んじる[美|び][観念|かんねん]とは[根本的|こんぽんてき]に[異|こと]なる。', english: 'Wabi-sabi is a traditional Japanese aesthetic sensibility that finds deep beauty in imperfection and impermanence, fundamentally different from Western aesthetic notions that prize perfection and permanence.' },
      { japanese: '「[侘|わ]び」は、もともと[孤独|こどく]や[侘|わ]びしさを[意味|いみ]したが、[茶|ちゃ]の[湯|ゆ]の[世界|せかい]において[千利休|せんのりきゅう]らによって[洗練|せんれん]され、[質素|しっそ]ながらも[精神的|せいしんてき]に[豊|ゆた]かな[境地|きょうち]を[指|さ]す[言葉|ことば]へと[昇華|しょうか]された。', english: '\'Wabi\' originally meant loneliness and desolation, but was refined in the world of the tea ceremony by figures such as Sen no Rikyu and sublimated into a word indicating a simple yet spiritually rich state of mind.' },
      { japanese: '「[寂|さ]び」は[時間|じかん]の[経過|けいか]によって[生|う]まれる[枯|か]れた[趣|おもむき]を[表|あらわ]し、[古|ふる]びた[器|うつわ]や[苔|こけ]むした[石|いし]、[錆|さ]びた[金属|きんぞく]に[宿|やど]る[深|ふか]みを[称|たた]える[感性|かんせい]である。', english: '\'Sabi\' expresses the refined interest born through the passage of time, a sensibility that praises the depth dwelling in aged vessels, moss-covered stones, and rusted metal.' },
      { japanese: 'この[美意識|びいしき]は[建築|けんちく]・[庭園|ていえん]・[文学|ぶんがく]・[陶芸|とうげい]など[日本文化|にほんぶんか]の[多|おお]くの[領域|りょういき]に[浸透|しんとう]しており、たとえば[金継|きんつ]ぎという[工芸|こうげい][技法|ぎほう]は、[割|わ]れた[器|うつわ]を[金|きん]で[繕|つくろ]うことで[傷|きず]の[歴史|れきし]を[肯定|こうてい]するという[侘|わ]び・[寂|さ]びの[精神|せいしん]を[体現|たいげん]している。', english: 'This aesthetic sensibility has permeated many domains of Japanese culture including architecture, gardens, literature, and ceramics; for example, the craft technique of kintsugi — repairing broken vessels with gold — embodies the spirit of wabi-sabi by affirming the history of the damage.' },
      { japanese: '[近年|きんねん]、[侘|わ]び・[寂|さ]びは[欧米|おうべい]のデザイン・[建築|けんちく]・ライフスタイル[誌|し]においても[脚光|きゃっこう]を[浴|あ]びており、[過剰|かじょう]な[消費|しょうひ]や[装飾|そうしょく]に[疲|つか]れた[現代人|げんだいじん]の[心|こころ]を[捉|とら]えている。', english: 'In recent years, wabi-sabi has also been attracting attention in Western design, architecture, and lifestyle publications, capturing the hearts of modern people fatigued by excess consumption and ornamentation.' },
      { japanese: 'しかし、この[美学|びがく]の[核心|かくしん]が[翻訳|ほんやく]や[商業化|しょうぎょうか]のプロセスを[通|とお]じて[希薄化|きはくか]されるという[危惧|きぐ]もあり、その[思想的|しそうてき][深度|しんど]を[保持|ほじ]したまま[国際的|こくさいてき]に[普及|ふきゅう]させることの[困難|こんなん]さを[示|しめ]している。', english: 'However, there is also concern that the core of this aesthetics is being diluted through processes of translation and commercialization, demonstrating the difficulty of disseminating it internationally while retaining its philosophical depth.' },
    ],
    vocabulary: [
      { word: '無常', reading: 'むじょう', english: 'impermanence; transience' },
      { word: '昇華', reading: 'しょうか', english: 'sublimation; elevation to a higher form' },
      { word: '金継ぎ', reading: 'きんつぎ', english: 'kintsugi; gold repair of ceramics' },
      { word: '体現', reading: 'たいげん', english: 'embodiment; personification' },
      { word: '脚光を浴びる', reading: 'きゃっこうをあびる', english: 'to bask in the spotlight; to attract attention' },
      { word: '希薄化', reading: 'きはくか', english: 'dilution; thinning out' },
      { word: '危惧', reading: 'きぐ', english: 'fear; apprehension; concern' },
      { word: '核心', reading: 'かくしん', english: 'core; crux; heart of the matter' },
    ],
  },
  {
    id: 'r043',
    title: '[社会変容|しゃかいへんよう]と[個人|こじん]の[在|あ]り[方|かた]',
    titleEn: 'Social Change and the Role of the Individual',
    level: 'N1',
    topic: 'social change',
    paragraphs: [
      { japanese: '[現代|げんだい]社会は、[技術革新|ぎじゅつかくしん]・[人口動態|じんこうどうたい]の[変化|へんか]・[気候変動|きこうへんどう]という[三|みっ]つの[大|おお]きな[力|ちから]によって[根本的|こんぽんてき]な[変容|へんよう]を[遂|と]げつつある。', english: 'Contemporary society is undergoing a fundamental transformation driven by three great forces: technological innovation, demographic change, and climate change.' },
      { japanese: '[個人|こじん]は、こうした[激動|げきどう]の[時代|じだい]においてどのような[主体性|しゅたいせい]を[持|も]ち、いかに[社会|しゃかい]と[関|かか]わり[合|あ]うべきかという[問|とい]は、かつてなく[切実|せつじつ]な[問題|もんだい]として[私|わたし]たちの[目前|もくぜん]に[突|つ]き[付|つ]けられている。', english: 'The question of what kind of agency individuals should possess in such a turbulent era and how they should engage with society is being thrust before us as an issue of unprecedented urgency.' },
      { japanese: '[ハンナ・アーレント|はんなあーれんと]が「[公的|こうてき]領域への[参加|さんか]」を[人間|にんげん]の[本質的|ほんしつてき]条件として[挙|あ]げたように、[民主主義|みんしゅしゅぎ]の[維持|いじ]には、[情報|じょうほう]の[吟味|ぎんみ]と[批判的|ひはんてき][思考|しこう]に[基|もと]づいた[公共|こうきょう]への[積極的|せっきょくてき]な[関与|かんよ]が[不可欠|ふかけつ]である。', english: 'As Hannah Arendt cited \'participation in the public realm\' as an essential condition of human existence, active engagement with the public sphere based on critical scrutiny of information is indispensable for the maintenance of democracy.' },
      { japanese: 'しかし、[情報|じょうほう]の[氾濫|はんらん]とSNSの[普及|ふきゅう]は、[個人|こじん]を[同質的|どうしつてき]な[意見|いけん]のみに[囲|かこ]まれた「[情報|じょうほうの]繭|まゆ」に[閉|と]じ[込|こ]め、[社会的|しゃかいてき][分断|ぶんだん]を[深|ふか]める[危険性|きけんせい]をはらんでいる。', english: 'However, the flood of information and the spread of social media carry the danger of confining individuals in \'information cocoons\' surrounded only by homogeneous opinions, deepening social division.' },
      { japanese: '[社会変容|しゃかいへんよう]に[受動的|じゅどうてき]に[従|したが]うのではなく、[自|みずか]ら[変容|へんよう]の[担|にな]い[手|て]となることが[可能|かのう]であるという[視座|しざ]は、[個人|こじん]の[存在|そんざい]を[単|たん]なる[歴史|れきし]の[客体|かくたい]から[主体|しゅたい]へと[転換|てんかん]する[契機|けいき]を[与|あた]える。', english: 'The perspective that it is possible not to passively conform to social transformation but to oneself become a bearer of transformation provides the opportunity to shift the individual\'s existence from a mere object of history to a subject.' },
      { japanese: '[個人|こじん]と[社会|しゃかい]の[関係性|かんけいせい]を[絶|た]えず[問|と]い[直|なお]すという[営|いとな]みこそが、[変化|へんか]の[激|はげ]しい[時代|じだい]を[生|い]き[抜|ぬ]くための[知的|ちてき][基盤|きばん]となるのではないだろうか。', english: 'Is it not the very practice of continually questioning the relationship between the individual and society that becomes the intellectual foundation for living through an era of intense change?' },
    ],
    vocabulary: [
      { word: '変容', reading: 'へんよう', english: 'transformation; metamorphosis' },
      { word: '主体性', reading: 'しゅたいせい', english: 'agency; autonomy; subjectivity' },
      { word: '切実', reading: 'せつじつ', english: 'urgent; pressing; poignant' },
      { word: '氾濫', reading: 'はんらん', english: 'flood; overflow; proliferation' },
      { word: '分断', reading: 'ぶんだん', english: 'division; splitting; severance' },
      { word: '視座', reading: 'しざ', english: 'standpoint; vantage point' },
      { word: '契機', reading: 'けいき', english: 'opportunity; trigger; turning point' },
      { word: '営み', reading: 'いとなみ', english: 'activity; practice; endeavor' },
    ],
  },
  {
    id: 'r044',
    title: '[科学的知識|かがくてきちしき]の[進歩|しんぽ]と[倫理|りんり]',
    titleEn: 'Scientific Advancement and Ethics',
    level: 'N1',
    topic: 'scientific advancement',
    paragraphs: [
      { japanese: '[二十一世紀|にじゅういちせいき]に[入|はい]り、[遺伝子工学|いでんしこうがく]・[人工知能|じんこうちのう]・[量子|りょうし]コンピューティングといった[先端科学技術|せんたんかがくぎじゅつ]は、[人類|じんるい]がこれまで[不可能|ふかのう]だと[考|かんが]えてきた[問題|もんだい]の[解決|かいけつ]を[現実的|げんじつてき]な[射程|しゃてい]に[収|おさ]めつつある。', english: 'Entering the 21st century, cutting-edge science and technology such as genetic engineering, artificial intelligence, and quantum computing are bringing within realistic range solutions to problems humanity has hitherto considered impossible.' },
      { japanese: 'しかし、[科学技術|かがくぎじゅつ]の[加速度的|かそくどてき]な[進歩|しんぽ]は、[倫理的|りんりてき][規範|きはん]の[整備|せいび]を[大幅|おおはば]に[上回|うわまわ]るペースで[進|すす]んでおり、「[コリンリッジのジレンマ|こりんりっじのじれんま]」に[代表|だいひょう]されるように、[技術|ぎじゅつ]の[影響|えいきょう]を[初期段階|しょきだんかい]で[把握|はあく]・[制御|せいぎょ]することの[根本的|こんぽんてき]な[困難|こんなん]さが[指摘|してき]されている。', english: 'However, the accelerating progress of science and technology is advancing at a pace far exceeding the development of ethical norms, and as represented by the \'Collingridge dilemma,\' the fundamental difficulty of grasping and controlling the effects of technology at an early stage has been pointed out.' },
      { japanese: '[生命倫理|せいめいりんり]の[領域|りょういき]においては、ゲノム[編集|へんしゅう]技術「クリスパー」の[登場|とうじょう]により、[遺伝性疾患|いでんせいしっかん]の[根絶|こんぜつ]と「[デザイナーベビー|でざいなーべびー]」の[実現可能性|じつげんかのうせい]が[同|おな]じ[技術|ぎじゅつ]の[表裏|ひょうり]として[浮上|ふじょう]しており、[科学|かがく]の[善用|ぜんよう]と[悪用|あくよう]の[境界線|きょうかいせん]がいかに[曖昧|あいまい]であるかを[示|しめ]している。', english: 'In the realm of bioethics, the emergence of the CRISPR genome editing technology has brought the eradication of hereditary diseases and the feasibility of \'designer babies\' to the surface as two sides of the same technology, demonstrating how ambiguous the boundary between beneficial and harmful use of science is.' },
      { japanese: '[人工知能|じんこうちのう]の[分野|ぶんや]でも、[偏|かたよ]ったデータに[基|もと]づく[アルゴリズム|あるごりずむ]が[差別的|さべつてき]な[判断|はんだん]を[下|くだ]すという「[アルゴリズムバイアス|あるごりずむばいあす]」の[問題|もんだい]は、[技術的|ぎじゅつてき][中立性|ちゅうりつせい]という[幻想|げんそう]を[打|う]ち[砕|くだ]き、[設計者|せっけいしゃ]の[価値観|かちかん]が[技術|ぎじゅつ]に[埋|う]め[込|こ]まれることの[不可避性|ふかひせい]を[露|あら]わにしている。', english: 'In the field of artificial intelligence too, the problem of \'algorithmic bias\' — where algorithms based on skewed data render discriminatory judgments — shatters the illusion of technological neutrality and reveals the inevitability of designers\' values being embedded in technology.' },
      { japanese: '[科学|かがく]と[倫理|りんり]の[対話|たいわ]を[制度的|せいどてき]に[保証|ほしょう]するための[枠組|わくぐ]み、すなわち[科学技術|かがくぎじゅつ]・[イノベーション|いのべーしょん][政策|せいさく]への[倫理学者|りんりがくしゃ]・[社会科学者|しゃかいかがくしゃ]・[市民|しみん]の[参加|さんか]を[組|く]み[込|こ]んだ「[責任|せきにん]ある[研究|けんきゅう]・[イノベーション|いのべーしょん]」の[概念|がいねん]が[国際的|こくさいてき]に[普及|ふきゅう]しつつある。', english: 'The concept of \'Responsible Research and Innovation,\' which builds in the participation of ethicists, social scientists, and citizens in science, technology, and innovation policy — a framework to institutionally guarantee dialogue between science and ethics — is spreading internationally.' },
      { japanese: '[科学的知識|かがくてきちしき]の[進歩|しんぽ]は[人類|じんるい]に[多大|ただい]な[恩恵|おんけい]をもたらす[潜在力|せんざいりょく]を[持|も]つが、それが[真|しん]に[人間|にんげん]の[尊厳|そんげん]と[福祉|ふくし]に[資|し]するものとなるためには、[問|と]いを[立|た]て[続|つづ]ける[哲学的|てつがくてき][知性|ちせい]と、[合意|ごうい]を[形成|けいせい]する[民主的|みんしゅてき][過程|かてい]が[科学|かがく]と[協働|きょうどう]することが[不可欠|ふかけつ]である。', english: 'Scientific knowledge has the potential to bring great benefits to humanity, but for it to truly serve human dignity and welfare, it is indispensable that philosophical intelligence that continues to pose questions, and democratic processes that form consensus, cooperate with science.' },
    ],
    vocabulary: [
      { word: '倫理', reading: 'りんり', english: 'ethics; morality' },
      { word: '遺伝子工学', reading: 'いでんしこうがく', english: 'genetic engineering' },
      { word: '規範', reading: 'きはん', english: 'norm; standard; rule' },
      { word: '根絶', reading: 'こんぜつ', english: 'eradication; extermination' },
      { word: '幻想', reading: 'げんそう', english: 'illusion; fantasy' },
      { word: '尊厳', reading: 'そんげん', english: 'dignity; sanctity' },
      { word: '協働', reading: 'きょうどう', english: 'collaboration; working together' },
      { word: '潜在力', reading: 'せんざいりょく', english: 'latent potential; dormant capacity' },
    ],
  },
]

// Parse [kanji|reading] markers into { text, reading } segments
export function parseRuby(text: string): { text: string; reading?: string }[] {
  const segments: { text: string; reading?: string }[] = []
  const regex = /\[([^\|]+)\|([^\]]+)\]/g
  let lastIdx = 0
  let match
  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIdx) {
      segments.push({ text: text.slice(lastIdx, match.index) })
    }
    segments.push({ text: match[1], reading: match[2] })
    lastIdx = match.index + match[0].length
  }
  if (lastIdx < text.length) {
    segments.push({ text: text.slice(lastIdx) })
  }
  return segments
}
